### ISSUE TITLE
infinitemac.org

### ISSUE THREAD

**Issue by mihaip** [mihaip/infinite-mac#100]
- [x] Choose domain name: 
    - ✅  infinitemac.org ($12/year) 
    - ❌ macos.museum ($45/year)
    - ❌ system.software (but it’s $2700/year) 
    - ❌ scrape domainr for macos.* or system.* options
- [x] About page with blog posts, donation information
- [ ] Browse UI
    - [x] Make "Infinite Mac" in footer use Chicago 12 and rainbow color. Clicking on it should return back to the start page.
    - [x] List view
    - [x] Emulator does not fully stop when returning back to the main screen (at least after running System 7, the 100% CPU use persists)
    - [x] Slightly reduce size of Apple logo in medium bezel size
    - [x] Ensure that we redirect to the HTTPS version
    - [x] Add specific release date as subtitle to each disk
    - [x] Embed intro/walkthrough YouTube video in "About" dialog
    - [x] Remove old `AppDomain` component
    - [x] Preserve/restore scroll position when going back to the main screen from a machine
    - [ ] #141
    - [ ] #142
    - [x] Permalinks for each release
    - [x] Redirect system7.app etc. to new URLs
    - [x] Update welcome text to explain how to set up AppleTalk zones
    - [x] Support for command-clicking on "Run" button to open in a new window
    - [x] More prominent "Done" button for returning to the main screen
- [x] Run with custom settings
    - [x] Overriding emulator/machine if multiple are supported
    - [x] Configuring LocalTalk zone
- [ ] Disk images (version history: [early releases](https://en.wikipedia.org/wiki/Classic_Mac_OS#Release_history), [System 6](https://en.wikipedia.org/wiki/System_6#Version_history), [more history](https://web.archive.org/web/20160810183725/http://www.mac512.com/macwebpages/system.htm), [System 7](https://en.wikipedia.org/wiki/System_7#Releases), [MacOS 8](https://en.wikipedia.org/wiki/Mac_OS_8#Versions), [Mac OS 9](https://en.wikipedia.org/wiki/Mac_OS_9#Version_history), [compatibility matrix](https://docs.google.com/spreadsheets/d/1us6SCBgVs8NqbxofJXTmHDeK3nKQJpcgya2nWC9_t2w/edit), [Macintosh Secrets version history](http://www.toddp.com/classic/Software%20Install/Apple%20Support%20Documents/Macintosh%20Secrets/Mac%20Secrets%204th%20ed./ch06.pdf))
    - [x] 1984: 0.97/1.0
    - [x] 1984: 1.1
    - [x] 1985: 2.0
    - [x] 1985: 2.1
    - [x] 1986: 3.0
    - [ ] 1986: 3.1 (buggy, hard to find)
    - [x] 1986: 3.2
    - [x] 1987: 3.3
    - [x] 1987: 4.0
    - [x] 1987: 4.1
    - [x] 1987: 5.0
    - [x] 1987: 5.1
    - [x] 1988: 6.0
    - [ ] 1988: 6.0.1 (buggy, hard to find)
    - [x] 1988: 6.0.2
    - [x] 1989: 6.0.3
    - [x] 1989: 6.0.4
    - [x] 1990: 6.0.5
    - [ ] 1990: 6.0.6 (buggy, hard to find)
    - [x] 1990: 6.0.7
    - [x] 1991: 6.0.8
    - [x] 1991: 7.0
    - [ ] 1991: 7.0.1 (notable?)
    - [ ] 1992: 6.0.8L
    - [x] 1992: 7.1
    - [x] 1993: 7.1.1 (System 7 Pro)
    - [ ] 1994: 7.1.2 (first PPC release, not bootable in SheepShaver)
    - [x] 1994: 7.5 
    - [x] 1995: 7.5.1 (first to use Mac OS terminology)
    - [x] 1995: 7.5.2 (PCI PowerMacs only)
    - [x] 1996: 7.5.3 
    - [x] 1996: 7.5.5 
    - [x] 1997: 7.6
    - [ ] 1997: 7.6.1 (notable?)
    - [x] 1997: 8.0
    - [x] 1998: 8.1
    - [x] 1998: 8.5
    - [ ] 1998: 8.5.1 (notable?)
    - [x] 1999: 8.6
    - [x] 1999: 9.0
    - [ ] 2000: 9.0.2
    - [ ] 2000: 9.0.3
    - [x] 2000: 9.0.4 (consider redoing image with bigger disk to avoid having to cut down as much)
 - [ ] Add more machine options ([gestalt IDs](https://www.emaculation.com/forum/viewtopic.php?t=8836), [ROMs spreadsheet](https://docs.google.com/spreadsheets/d/1wB2HnysPp63fezUzfgpk0JX_b7bXvmAg6-Dk7QDyKPY/edit#gid=840977089))
    - [x] Mac 128K
    - [x] Mac 512Ke
    - [ ] Mac II with 16 colors
    - [ ] Mac II with millions of colors
    - [ ] Mac II in black-and-white with Portrait display
    - [x] More specific PowerMac than "Old World"
    - [x] More specific PowerMac than "New World"
- [x] Check version history agains the [Macintosh Secrets book](http://www.toddp.com/classic/Software%20Install/Apple%20Support%20Documents/Macintosh%20Secrets/Mac%20Secrets%204th%20ed./ch06.pdf)
- [x] Restore System 1.0 icons (finder icons have a "42" in them, and floppy icons have a black tab)
- [x] Use beige bezels only for [pre-1987 machines](https://vintagemacmuseum.com/when-the-mac-plus-changed-from-beige-to-platinum/)
- [x] Alternate library disk image for MFS-only operating systems (System 2.0 and earlier). Include MacPaint, MacWrite, etc.
- [ ] Compatibility
    - [x] System 1.0 does not mount the Infinite HD (MFS) image
    - [x] Sound does not work in the Mac IIfx Basilisk II image
    - [ ] #145
    - [ ] #146
- [x] Importing files and disk images does not work in OS'es without idlewait support (e.g. System 7) -- add alternate mechanism
- [x] Defragment all disk images
- [ ] Mobile improvements
    - [x] Shrink browser screen size when on a phone screen
    - [x] Show controls below the screen when in small bezel mode
    - [x] #7
    - [x] #79
    - [ ] #86
    - [x] Don't use hover CSS selector for "Configure" button on mobile, since it makes the "Run" button take two taps

**Comment by that-ben** [comment]
I vote for infinitemac.org
It's cute, it's small and it fits in our pocket. 💰
Plus, people have been slowly getting used to the Infinite Mac brand name for almost a year now so the community already easily recognizes and trusts this name.

**Comment by that-ben** [comment]
In the list of disk images above, I could supply all of them if you wanted.  Also, I would highly discourage making a System 3.1 environment as this was the worst Mac OS release ever made.  It contained serious bugs that would corrupt the hard drive or floppy disk on which it ran.  This release should be thrown in an erupting volcano and be forgotten forever ;-)

**Comment by mihaip** [comment]
@that-ben do you have any pointers for an accurate System 0.97/1.0 disk image? The ones I've been able to find are all not quite right:
1. https://archive.org/details/MacintoshSystemSoftware1.0AppleComputerInc.1984 has a missing icon for the system disk (and appears to have been modified on a French system at some point, based on the modification dates)
2. https://www.macintoshrepository.org/7617-mac-os-0-x-1-0-pre-release- appears to be a modified version, where Chicago 12 has been replaced with a Marker Felt-like font
3. https://winworldpc.com/product/mac-os-0-6/system-1x is same edited font one
4. https://www.macintoshrepository.org/34467-macintosh-system-software-1-0-redump- manually undoes the Chicago 12 font, but has a custom desktop pattern 

For now I've gone with a fixed up version of the last one, but it still doesn't feel quite right.

**Comment by that-ben** [comment]
Hi Mihai, alas, the reason for the modified/patched System 1.0 disk images that are lying around on the internet is because the only actual physical copies that have both been found and archived were corrupted.  Most sites are now hosting the same "modified" System 1.0 as an almost perfect substitute, but it's not museum perfect.  TBH, I think most users will never really know the difference...

**Comment by mihaip** [comment]
@that-ben and anyone else following this bug: https://infinitemac.org now has all releases through 6.0.8. Let me know if I missed any and/or anything notable in the release highlights.

**Comment by that-ben** [comment]
hello (again)
For a second time in less than 6 months, I am genuinely impressed by the amount of work you've put into this collection of WASM emulators and they seem to be working great. The little drop down to choose which ROM you want to boot any given system release is fantastic. Not to mention that just the fact that you left 3.1 out alone is worth the wait! ;-)
![the-wolf-of-wall-street-clap](https://user-images.githubusercontent.com/13210399/223421325-f3be206c-6635-4aec-899a-64b1a4ba7c91.gif)

**Comment by that-ben** [comment]
Out of curiosity, what motivated you to choose the platinum bezel/look for the System 4.0 (or even 4.1) box on InfiniteMac.org?

**Comment by mihaip** [comment]
The bezel color is based on the machine, and 4.0 only runs on the SE (at least, that's what I've observed in my local testing with Mini vMac). The SE was the first machine to use the platinum color.

You can end up with beige bezels for subsequent releases if you customize the machine type to back to a 512Ke or Plus:
<img width="449" alt="image" src="https://user-images.githubusercontent.com/513813/224894316-6e585cd3-f4ec-4beb-afd7-669cf5417f93.png">

**Comment by that-ben** [comment]
Not sure what EveryMac.com is on to, but apparently the Macintosh II can boot as far back as System 2.0! https://everymac.com/systems/apple/mac_ii/specs/mac_ii.html

**Comment by mihaip** [comment]
I'm guessing that's due to the confusion between System Software releases and System versions -- System Software 2.0 shipped with System 4.0.

**Comment by that-ben** [comment]
The bit at 1:50 in the demo video is hilarious! I never read that before and this caught me by surprise wow

**Comment by mihaip** [comment]
@that-ben are you aware of any > 1.4 MB MFS images that will mount in Mini vMac with a Mac 128K ROM and running System 1.0? I'm looking to construct a mini version of Infinite HD for older systems, and I'm having trouble (the Mini vMac MFS blanks only go up to 1.4 MB, and those don't mount as secondary disks either)

**Comment by that-ben** [comment]
Gahh, I wasn't able to catch your message on time, would have loved to help you out.  Yes, 1.4MB is kind of a lot for the original 128K, but I'm wondering why not use a 20MB MFS image instead of only 1.4MB? I mean, why 1.4MB specifically? The 128K did not even support 1.4MB floppies (so it must be seeing it as a hard drive I suppose?)

**Comment by Iritscen** [comment]
Just a tiny note that you are missing the word "be" in the sentence "Files can imported and exported using drag and drop…".  I love the website though, great design!

**Comment by mihaip** [comment]
@Iritscen thanks for reporting those, should be fixed now.

**Comment by mihaip** [comment]
Declaring this done I've filed other GitHub issues for the lingering tasks (#141, #142, #143, #144, #145, #146).
