### ISSUE TITLE
Could the chunk prefetch optimizer explicitly name the disk images?

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#101]
I have a request: Can we have it so that the console explicitly names the disk images instead of just calling all of them "/Disk" ? It would be more efficient in trying to optimize the chunk preloading.  Thx

![Capture](https://user-images.githubusercontent.com/13210399/218318461-ba863543-2c85-472b-843b-17f985a9dc8b.PNG)

**Comment by mihaip** [comment]
Sure, easy enough to fix.
