### ISSUE TITLE
(low priority) Pixel scaling is slightly wrong, better smoothing required?

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#106]
I know this is very low priority, but I'm leaving this here as something easy that could be looked at after everything else.

We need to do something about the pixel up-scaling in Infinite Mac emulators when they go full screen.  Perhaps we need better smoothing of the HTML canvas via a simple CSS rule like this:

```
.fullscreen .Mac-Screen {
  image-rendering: auto;
}
```

It makes a huge improvement:

![pixelated](https://user-images.githubusercontent.com/13210399/220129601-f789fce1-7b01-4628-8ee8-4fbfe66252b8.png)

![auto](https://user-images.githubusercontent.com/13210399/220129621-826a3510-1eea-493e-81d1-3f131755eecb.png)

**Comment by mihaip** [comment]
That's a good observation, will fix.
