### ISSUE TITLE
Link in settings for switching to Powermac in System 7 and Mac OS 8

### ISSUE THREAD

**Issue by BiggerJ** [mihaip/infinite-mac#112]
I found the link in your blog to system7.app's [Powermac (aka PPC) mode](https://system7.app/?domain=system7-ppc.app) - making this an official feature in system7.app and macos8.app would be a good idea for compatibility purposes. The best way to implement this would be to have there be a link in the Settings menu, along with a note that the emulation will reset. (Of course, when in Powermac mode, there would instead be a link to the original Motorola 68K processor mode - be sure to mention that, or people may think you mean 68 kilobytes.)

**Comment by mihaip** [comment]
This is what I have in mind for the infinitemac.org site, which is under development. You can follow along at #100.
