### ISSUE TITLE
Software request: the Batman DOOM 2 total conversion

### ISSUE THREAD

**Issue by BiggerJ** [mihaip/infinite-mac#113]
Before they made Zeno Clash, Rock of Ages and The Eternal Cylinder, ACE Team made Batman DOOM, an incredible total conversion mod for Doom 2, originally made for Mac. If you add it, please follow the instructions below - the widely available version is a modified version that gets around quirks of the PC version of Doom 2.

1. Download the Mac version of the mod from https://www.doomworld.com/3ddownloads/batmantc/[Batman.sit
2. Download Doominator from https://macintoshgarden.org/games/doom-editing-suite (it'll be in a pack with other utilities)
3. Following the 'Installing BD' instructions file included with the mod, use Doominator to apply the two included patches to Doom 2 in order, Patch 1 then Patch 2. (According to [this forum post](https://www.doomworld.com/forum/topic/103495-most-creative-dehacked-custom-monster/?do=findComment&comment=1948354), you might need to experiment with multiple versions of Doom 2.) There's two options after that - put the resulting modified application in it own folder with the custom music folder, resulting in the player needing to find the base Doom 2 WAD upon request, or replace the standard Doom 2 application and music folder with the new ones.

I think the Batman WAD file needs to be dragged onto the app. If Doom 1 is also present, double-clicking it might open the wrong game. You might have to write a readme file saying to drag the wad onto the modded application (or, more conveniently, give some folders blank icons and write the instructions in their titles - making sure the folder is in the 'by Icon' view).

**Comment by mihaip** [comment]
This is a bit too esoteric to add. However, you can use the Saved HD feature to do all this and persist it across uses.
