### ISSUE TITLE
Add color version of SimCity

### ISSUE THREAD

**Issue by mihaip** [mihaip/infinite-mac#115]
From https://github.com/mihaip/infinite-mac/issues/100#issuecomment-1458109772:
> SimCity, that you already have on the Infinite HD, could be replaced by version 1.14c instead of 1.11 which would allow it to run in 16 colors mode. That's how I remember that game and I think the color version aged better and will attract more kids to want to play it. Note that version 1.14c still works just as good in B&W mode (it's hybrid): https://emulate-in-browser.macintoshrepository.org/?macmodel=6&disk1=MacOS753.dsk&disk2=9781_SimCity-1.4c.dsk&r

**Comment by that-ben** [comment]
This reminds me also that I forgot to ask you, but do you think you could take a look perhaps at a way that we could throttle down BasiliskII.js down a notch via some sort of user setting or in the BasiliskIIPrefs.txt? I'm not even sure the original BasiliskII builds had that sort of thing.  On a very old Windows build, I tweaked it to sleep 9ms between each frame which made it somewhat usable with some games that ran too fast, but I would ultimately like if we could have something like Mini vMac has where you can hit a key combo and make it run at 1X, 2X, 4X, 8X... This is what the really old BasiliskII build had that helped a little:

![image](https://user-images.githubusercontent.com/13210399/223748682-d6872289-8f1d-41c5-9d4a-1ceb0cf4990c.png)
