### ISSUE TITLE
Recognize upper-case file extensions

### ISSUE THREAD

**Issue by BiggerJ** [mihaip/infinite-mac#117]
I just tried running a .ISO file, but it wouldn't work until I renamed it to a .iso file.

**Comment by that-ben** [comment]
I can confirm that MacOS9.app actually puts the .ISO (uppercase) file in The Outside World > Downloads instead of mounting it.
![dasdas](https://user-images.githubusercontent.com/13210399/224558148-ceb4bd54-bc3e-4048-ba0f-a3f784dd2f91.PNG)

**Comment by mihaip** [comment]
Thanks for reporting, should be fixed now.
