### ISSUE TITLE
[low priority] SETTINGS, ABOUT & DONATE links crash the MacOS9.app integration on MR?

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#119]
On the MR integration of MacOS9.app, whenever we click on "Settings" in the bottom bezel, on "About" or on "Donate" in the footer, the app's root DIV instantly becomes 100% empty with this React error in the console:
`Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

https://emulate-in-browser.macintoshrepository.org/?macmodel=5&disk1=MacOS904.dsk

![dasdsa](https://user-images.githubusercontent.com/13210399/226112903-86bb77f2-e870-43d2-bf9c-b23cb27cbe78.PNG)

Any idea how we could fix this so people can use the settings window, see your credits and donate to InfiniteMac on MR? Other links such as "Load File" and "Full Screen" work just fine.

**Comment by mihaip** [comment]
There's a new `<div id="dialog-root"></div>` root node that you'll need to add to your HTML, see https://github.com/mihaip/infinite-mac/commit/59d6b471dcb08b3fdf6acc3a7c7d4ab068b1aaa4#diff-c2cc24bc9001b11b6add48a4cd8f893d5d6c6e4d1bd254158bd14ab997f552cd for where I added it to mine.

**Comment by that-ben** [comment]
Ah, crap! I completely missed the index.html changes! Thanks!
