### ISSUE TITLE
Sound does not work on Mac OS 9

### ISSUE THREAD

**Issue by cintoli** [mihaip/infinite-mac#120]
I use this configuration:

Model Name:	iMac
  Model Identifier:	iMac17,1
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	3.2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	32 GB
  System Firmware Version:	499.40.2.0.0
  OS Loader Version:	540.120.3~22
  SMC Version (system):	2.33f12
  Serial Number (system):	D25QL08QGG7V
  Hardware UUID:	B558442F-1325-58D6-9D5A-E86E68523186
  Provisioning UDID:	B558442F-1325-58D6-9D5A-E86E68523186

The browser is Safari. The OS is MacOS 12.6.3

**Comment by cintoli** [comment]
Thank you. It works now. I always forget that Safari is paranoid :-). And erratic, too, since sound works in macos8.app although sound is blocked!

**Comment by ChrDur1** [comment]
Same but I am using:
Windows 10 22H2 
Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz   2.60 GHz

**Comment by ChrDur1** [comment]
actually nvm i had to go and select the output for the machine as built in manually

**Comment by mihaip** [comment]
Ah yes, I forgot that I had to select the output device in the control panel (which modifies a preference file) -- that was lost when I rebuilt the image recently. Will restore it.
