### ISSUE TITLE
Infinitemac instances fail to load on Safari 14.1.2

### ISSUE THREAD

**Issue by vga-256** [mihaip/infinite-mac#125]
All of the System.* instances fail to load, and produce a blank page in Safari 14.1.2 on my MBP running Big Sur 11.7.2

Web Inspector errors are the same regardless of System.* instance:

```
ReferenceError: Can't find variable: SharedArrayBuffer
	cu (2.545e0bfc.chunk.js:2:210389)
	(anonymous function) (2.545e0bfc.chunk.js:2:212494)
	mo (2.545e0bfc.chunk.js:2:176359)
	vu (2.545e0bfc.chunk.js:2:214205)
	Is (2.545e0bfc.chunk.js:2:230759)
	Is
	(anonymous function) (2.545e0bfc.chunk.js:2:250084)
	Rs (2.545e0bfc.chunk.js:2:227494)
	bs (2.545e0bfc.chunk.js:2:223580)
	bs
	(anonymous function) (2.545e0bfc.chunk.js:2:172848)
	(anonymous function) (2.545e0bfc.chunk.js:2:250084)
	Ki (2.545e0bfc.chunk.js:2:172794)
	Qi (2.545e0bfc.chunk.js:2:172729)
	Bs (2.545e0bfc.chunk.js:2:232493)
	(anonymous function) (2.545e0bfc.chunk.js:2:250084)
	(anonymous function) (2.545e0bfc.chunk.js:2:231679)
	U (2.545e0bfc.chunk.js:2:249143)
	(anonymous function) (2.545e0bfc.chunk.js:2:247865)
```
```
[Error] ReferenceError: Can't find variable: SharedArrayBuffer
	(anonymous function) (2.545e0bfc.chunk.js:2:247942)
```
`[Log] Service worker registered (main.4ec1cadd.chunk.js, line 1)`
`[Log] Service worker active (main.4ec1cadd.chunk.js, line 1)`
`[Error] Failed to load resource: the server responded with a status of 404 () (performance.min.js.map, line 0)`

The last error resolves to: https://static.cloudflareinsights.com/beacon.min.js/performance.min.js.map: "Invalid route"

**Comment by mihaip** [comment]
Thanks for the report, I believe this should be fixed (I don't have a machine that still runs Safari 14.2, but there was a `SharedArrayBuffer`-specific issue that I was able to reproduce and fix).
