### ISSUE TITLE
MR implementations of SheepShaver.js and BasiliskII.js fail to load only on iPhone?

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#132]
Both recent-ish WASM builds of SheepShaver.js and BasiliskII.js on MR are failing to load what seemingly is a JS file and this only seems to happen on iPhone, iOS 16.4, default Safari browser.  I believe it was working on iOS 15 but I'm not 100% sure.  No other device I've tried it on seems to have this issue.  I have tried to capture the iOS console but all I can get is that it's failing to load a resource exactly at this line: self.Module=r,importScripts(e.jsUrl)}(t.config)};

You can try it by yourself at this URL, I've put an overlay DIV that will show what I could capture from the console.  Having a modern Mac would greatly help in debugging on iPhone, which I unfortunately don't currently have.
https://emulate-sheepshaverjs.macintoshrepository.org/?disk1=MacOS904.dsk

![IMG_0072](https://user-images.githubusercontent.com/13210399/228608560-f0e01bdb-f295-4de6-9b25-0eed419c68cf.jpg)

**Comment by that-ben** [comment]
Note: I updated all the files to the latest build and the issue is still alive.  I now feel like MR might be missing a file that is only required for iPhone.

**Comment by mihaip** [comment]
Can you make sure that you're serving the `.jsz` files with a `text/javascript` MIME type? Looking at https://emulate-sheepshaverjs.macintoshrepository.org/static/media/SheepShaver.13ec7474.jsz, I'm not seeing `Content-Type` header:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/513813/228659802-def52599-50f1-4bcb-96a9-fd030bc51e4d.png">

Whereas https://infinitemac.org/static/media/SheepShaver.13ec7474.jsz has one:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/513813/228659611-ef361d90-8124-4ac2-a6d9-f089fde1274e.png">

**Comment by that-ben** [comment]
NO WAY! Wow, I totally missed that! In the .htacces I already had:
AddType application/wasm .wasm
AddType application/wasm .wasmz
AddType multipart/mixed .chunk

But I've just added what you suggested and it works perfectly fine now, indeed! Wow... Some days, no matter how much I try, I just can't see what should be obvious.  **Thank you so much** for waking me up, I appreciate it!

**Comment by mihaip** [comment]
Glad it worked.
