### ISSUE TITLE
Touch input issues on tablets (Android/iOS)

### ISSUE THREAD

**Issue by parkerlreed** [mihaip/infinite-mac#134]
Noticing consistent behavior no matter the browser. 

Tap and drag inconsistently works and tapping one area and then another will act like you dragged from one to the other. 

Going full screen the cursor starts out in the upper left pretty much lined up with your finger but by the time you get to the bottom right it has a considerable offset. 

https://user-images.githubusercontent.com/841440/228720436-237f0916-71d5-469e-b42c-2088af27cc64.mp4

**Comment by parkerlreed** [comment]
I'm seeing the same fullscreen behavior on an iPad Air 2 on iOS 14

**Comment by parkerlreed** [comment]
It appears like any platform with touch and going full screen has this behavior because I just reproduced it on a Linux laptop with Chrome.

**Comment by mihaip** [comment]
The coordinate conversion between touch events and the Mac screen was not taking into account the scaling factor, that should be fixed now.

**Comment by parkerlreed** [comment]
Working great! Thank you.
