### ISSUE TITLE
Add more fine-grained error tracking

### ISSUE THREAD

**Issue by mihaip** [mihaip/infinite-mac#156]
Based on current varzs, 10% of runs encounter an error. Most likely out of bounds accesses (#127, #97), but it would be good to validate.

```
"emulator_error:other": 4512,
"emulator_error:out_of_memory": 2770,
...
"emulator_starts": 43129,
```

Could also look into hooking up error reporting to Sentry.

**Comment by jllipatz** [comment]
Would it be possible to signal the "out of memory" errors the regular way for a Mac,? I mean signaling the error to the Mac OS, not stopping the web application. In that way 
- Any other application running on the infinite Mac will be still alive
- It will give the opportunity to track the error within MacOS.

**Comment by mihaip** [comment]
941b7e9cc81067929e3e0e880f54588eb839d3a2 did this.
