### ISSUE TITLE
macpaint 1.5 does not work properly 

### ISSUE THREAD

**Issue by enzyme69** [mihaip/infinite-mac#168]
I tested a few system, seems like macpaint 1.5 app does not work properly, especially with the preview during painting and drawing. I cannot see anything. If I do try to save, then I could see the final picture. But it's impossible to use because it does not show anything during painting sadly.

Can this be fixed somewhat?

**Comment by that-ben** [comment]
Hi, can you post:
1) The disk image download link
2) Your platform and browser specs (e.g. Windows 10, Firefox 111.0.1)
3) Which InfiniteMac.org emulator you used (e.g. System 2.1)

**Comment by mihaip** [comment]
MacPaint is a relatively old program, and expects to be run on a black-and-screen. If you're running it on a color machine (the default for System 7.1 and later) you'll need to switch it to black and white mode (from the Monitors control panel or Control Strip).
