### ISSUE TITLE
Question:  Binaries for Local use, if internet is not available?

### ISSUE THREAD

**Issue by ringtailedfox** [mihaip/infinite-mac#170]
Is there a way to compile binaries for say, Windows or Linux for offline/local use if internet connectivity is spotty, unreliable, slow or just unavailable?  I'd love to be able to run older mac software this way on a local basis!

**Comment by mihaip** [comment]
For offline use the native versions of Mini vMac, Basilisk II or SheepShaver should let you get an offline experience. You can find setup guides for them online, e.g. at:

https://www.emaculation.com/doku.php/mini_vmac
https://www.emaculation.com/doku.php/basilisk_ii
https://www.emaculation.com/doku.php/sheepshaver
