### ISSUE TITLE
Add Star Wars: Dark Forces

### ISSUE THREAD

**Issue by Gabe20052** [mihaip/infinite-mac#173]
This was a great first person shooter game! https://www.macintoshrepository.org/5997-star-wars-dark-forces

**Comment by that-ben** [comment]
Hi Gabe2005 :) I've just set it up here.  It works but playing it using the mouse is very hard, because it moves 10x too fast.  Playing with the keyboard works fine though: https://emulate-in-browser.macintoshrepository.org/?macmodel=5&disk1=MacOS86.dsk&disk2=9003_Dark-Forces.dsk

**Comment by mihaip** [comment]
The game is large enough that I'll most likely pick this up as part of the CD-ROM Library project (#166), as opposed to including it directly in Infinite HD.

**Comment by mihaip** [comment]
Dark Forces is now available in the CD-ROM library:
<img width="953" alt="image" src="https://github.com/mihaip/infinite-mac/assets/513813/9ced60c9-5f2e-48c7-a05c-b9d550096d8d">
