### ISSUE TITLE
Integer Scaling not applied in full screen?

### ISSUE THREAD

**Issue by rainyskye** [mihaip/infinite-mac#174]
It seems like integer scaling isn't being applied when full-screening?

When in the windowed(?) mode, it seems to be working properly, as zooming in while windowed you can see the pixels clearly, but as soon as you full screen, it becomes blurry again.

Macbook Pro - 16" M1 Max - macOS 13.3.1
Firefox 111.0.1
Safari 16.4

Windowed mode (zoomed)
<img width="460" alt="Screenshot 2023-04-21 at 2 02 31 am" src="https://user-images.githubusercontent.com/120244903/233430461-feaa6f31-dedc-4020-a77b-9e61f99d51ad.png">

Fullscreen mode
<img width="494" alt="Screenshot 2023-04-21 at 2 03 13 am" src="https://user-images.githubusercontent.com/120244903/233430593-5dd3b64c-c61c-4666-a7a9-65cb04b9e502.png">

I tried to make my screenshots match native res as much as possible, but you can see the difference pretty clearly :p

**Comment by mihaip** [comment]
This was a deliberate change, since there were too many rendering artifacts (#106), especially when the full screen was only making things slightly larger.

I can see this being an option though (something like: "Scaling: Auto | Smooth | Crisp")

**Comment by rainyskye** [comment]
Okay yeah, that makes sense, the only reason I'd use full-screen or anything is for games and stuff, as it's more of an immersive experience, but having rendering issues makes sense to it's removal.

An option could be nice, but if the issue still inherently exists then it's not a high priority/required

**Comment by that-ben** [comment]
Would you consider having full screen mode without up-scaling? That means with black border all around and the pixel is 1:1 (so perfectly crisp)

**Comment by livid** [comment]
For non-retina displays, `image-rendering: auto` may be better.

But for retina display, especially in full-screen mode, `image-rendering: pixelated` can provide really great integer scaling.

Here is SimCity 1.2 with `image-rendering: pixelated`:

<img width="1280" alt="Screenshot 2023-05-17 at 12 16 46 PM" src="https://github.com/mihaip/infinite-mac/assets/11427/43af63e1-593d-43c7-9bd0-b9247f518b01">

You can use media query to detect retina displays.

https://css-tricks.com/snippets/css/retina-display-media-query/

**Comment by that-ben** [comment]
eww, a Plymouth arcology

**Comment by Shogun38** [comment]
Has there been any update on this? The screen is quite blurry at full screen on my CRT.

**Comment by that-ben** [comment]
Meanwhile, just pop the browser console, type this and hit enter: `$('.App CANVAS').style.imageRendering = 'pixelated';`

**Comment by mihaip** [comment]
This is now available as a setting:

![Screenshot 2024-07-14 at 22 41 34@2x](https://github.com/user-attachments/assets/397ed17e-6264-4ab0-9b42-023bfa407ea8)
