### ISSUE TITLE
The Emscripten toolchain shouldn't live in an image pulled from a registry

### ISSUE THREAD

**Issue by seishun** [mihaip/infinite-mac#178]
The important bits of the Docker image used for building the emulators come from a parent image that gets pulled from GitHub Packages. That makes it complicated to make changes to the toolchain, e.g. to try a different version of Emscripten.

Perhaps it would make sense to merge https://github.com/mihaip/emscripten-docker into the Dockerfile here?

**Comment by mihaip** [comment]
Thanks for reminding me about this -- I had been meaning to switch to using `emsdk` to install the toolchain. Should be done now.
