### ISSUE TITLE
IntelligentPad errors during launch, won't start: 

### ISSUE THREAD

**Issue by gingerbeardman** [mihaip/infinite-mac#184]
![Screen shot 2023-05-17 at 22 07 54](https://github.com/mihaip/infinite-mac/assets/49612/095b151f-e10a-444e-8f8a-0b80a1c687f8)

Download here: 
- https://macintoshgarden.org/apps/intelligentpad 
- IntelligentPad-201E-68k.sit

Notes
- Same download launches without in BasiliskII native on macOS 12.6.5
- have tried System7.app and KanjiTalk7.app

## Errlog

[IntelligentPad 2.01 68K.errlog.zip](https://github.com/mihaip/infinite-mac/files/11502539/IntelligentPad.2.01.68K.errlog.zip)

```
---------------- MAC STACK TRACEBACK ------------------
ERR_Signal +001c
SYS_FailSysCall +009a
MACOS_GetDirIDFromPath +005c
S_TryPathOpen +01a6
NFilePathOpen +0066
NFILE_Open +0086
S_FileOpen +00a2
BFILE_Open +00a6
S_LoadLibFile +0102
RLIB_LoadLibFile +0014
S_LoadCoreResources +0088
RES_LibLoadInit +000e
VGM_LibLoadInit +0006
TKIT_LibLoadInit +0004
GW_LibLoadInit +0006
IPEntry__FiPPc +0080
main +000e
-------------------------------------------------------
Error (nd.dat, ndcore.dat or ndres.dat not loaded yet).
Check the application's search paths in resource STR# 10000.
ERROR:	Cannot load "Core" resource file
EXITING         cannot recover from error
```

**Comment by that-ben** [comment]
1) When you say System7.app and KanjiTalk7.app are you referring to the default Mac OS release with the default ROM in both cases?

and 2) What ROM and Mac OS are you running your native BasiliskII app with?

**Comment by gingerbeardman** [comment]
> When you say System7.app and KanjiTalk7.app are you referring to the default Mac OS release with the default ROM in both cases?

I'm referring to these two websites:
- https://system7.app which resolves to https://infinitemac.org/1996/System%207.5.3
- https://KanjiTalk7.app which resolves to https://infinitemac.org/1996/KanjiTalk%207.5.3

> What ROM and Mac OS release are you running your native BasiliskII app with?

My ROM
- af343f3f1362bf29cefd630687efaa25 1994-07 - 06684214 - LC,Quadra,Performa 630.ROM

I've tried
- 7.1
- 7.5.5 English
- J-7.5.3 Japanese

>  Are you trying to launch it from the emulated hard drive or from "The Outside World" ?

This was indeed the problem, I had moved it to the desktop from "The Outside World" but it seems that technically it's still located in there. I tried again just now and made a copy of the .sit file on the hard drive, expanded that, and it ran just fine!

Thanks!

**Comment by gingerbeardman** [comment]
Oh, and you can read about IntelligentPad at my blog: https://blog.gingerbeardman.com/2023/05/17/intelligentpad-component-based-drag-and-drop-software-creator/

Which has just been updated to let people know they can try IntelligentPad easily using Infinite Mac.
