### ISSUE TITLE
Add Macintosh Programmers Workbench MPW to the Infinite HD?

### ISSUE THREAD

**Issue by perdalum** [mihaip/infinite-mac#187]
Hi

What an amazing project! My first computer was a PowerBook 160 with System 7.1 and I've already spent an entire evening playing around with this :-) 

I tried to install MPW (https://www.macintoshrepository.org/545-macintosh-programmer-s-workshop-mpw-3-x), but the Macintosh needs a bit more storage.

Could the program (MPW) be added to the Infinite HD?

(or can I create an extra HD with enough storage?)

**Comment by that-ben** [comment]
Hi perdalum, you can simply click once on "Infinite HD" to select it, then in the menu bar, hit SPECIAL > ERASE... This will instantly give you an empty 1GB volume where you can install almost any software imaginable.  Back then, with 1GB you go a long way!

![asddas](https://github.com/mihaip/infinite-mac/assets/13210399/9b281f1f-3b6f-4448-9090-814c91b6c643)

**Comment by perdalum** [comment]
Hi that-ben

FANTASTIC! Thank you!

..Per
