### ISSUE TITLE
Add Copland Developer Release

### ISSUE THREAD

**Issue by donatj** [mihaip/infinite-mac#188]
Copland was a never commercially released successor to MacOS 7, it did however see release to developers. 

https://www.macintoshrepository.org/17006-copland-d9-copland-developer-release-tools-edition-

https://www.macintoshrepository.org/531-mac-os-8-0-copland-beta-builds-

**Comment by mihaip** [comment]
As far as I know this is not feasible, there are no emulators that can run Copland: https://www.emaculation.com/forum/viewtopic.php?t=9784

**Comment by n0stalgia-mac** [comment]
dingusppc can
