### ISSUE TITLE
Infinite MacSession doesn't "keep" settings and Dowloads/Saved documents

### ISSUE THREAD

**Issue by Chardonneret1** [mihaip/infinite-mac#190]
Hi,

I use Infinite Mac (System 7.0) with Firefox on a Mac Mini running iOS Monterey.

Each time I open my browser I have to reimport everything I had in the Saved and Download subfolders of the TheOutsideWorld folder. Also, If I add PrintToPDF to the extensions folder. It doesn't stay there between sessions. Could it be due to Firefox cache/security settings?

Kudos for an amazing website

Olivier

**Comment by mihaip** [comment]
Merging this into #182, which is also asking for persistence/state saving.
