### ISSUE TITLE
Rename “Done”

### ISSUE THREAD

**Issue by nclm** [mihaip/infinite-mac#192]
It’s not super clear that the “Done” button is a back button that stops the simulation. Especially if you were linked directly to a machine and don’t come from the homepage. Maybe it should be renamed “Close”. Or “Stop and close”. And/Or moved somewhere else where it’s not the main action button on the machine itself :)

**Comment by mihaip** [comment]
I've renamed it to "Home", which is still pretty short, and hopefully conveys the intent better.
