### ISSUE TITLE
infinitemac.org emulator pages, links are not clickable in the footer (about, donate, etc)

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#194]
System 1.0 and 2.0 pages work, but starting from System 2.1 and newer, all those links are seeming not clickable, at least under Firefox:

![dasdas](https://github.com/mihaip/infinite-mac/assets/13210399/0a0b79fa-6b46-4ef7-a346-0db9ca802f72)

**Comment by mihaip** [comment]
Thanks for noticing, it's caused by the CD-ROMs library at the bottom. Will fix.
