### ISSUE TITLE
Unable to checkout this repo in Windows

### ISSUE THREAD

**Issue by erichelgeson** [mihaip/infinite-mac#195]
I was interested in using some of the python code so was checking out this project to my Windows machine - it fails to checkout the main branch after clone due to `:` chars in file names, which is illegal in windows. eg: https://github.com/mihaip/infinite-mac/blob/main/CD-ROMs/Compilations/Power%20Computing%3A%20The%20Disc%20II.json

Not saying you should support a dev windows workflow for this project, but it would be nice to be able to checkout the project.

**Comment by mihaip** [comment]
TIL. I've replaced the colons with a different character ("﹕", which is a [small colon](https://www.fileformat.info/info/unicode/char/fe55/index.htm)), let me know if that works better.

**Comment by erichelgeson** [comment]
Works! Thanks for taking the time to look at it.
