### ISSUE TITLE
Please stop support for System 6.0.5.

### ISSUE THREAD

**Issue by Selvenity** [mihaip/infinite-mac#196]
System 6.0.5 cannot be launched with any machine because it's missing a hard drive.
Please stop support for this version of MacOS on Infinite Mac.

**Comment by mihaip** [comment]
Actually, this was a recent regression (60652fe2afea7d89b42d0ff8abfd5fc02e98c65b) that affected all Mini vMac-based instances. Will fix.

**Comment by mihaip** [comment]
Should be fixed now, https://infinitemac.org/1990/System%206.0.5 and other images will now boot.
