### ISSUE TITLE
Custom Floppy Image

### ISSUE THREAD

**Issue by upintheairsheep** [mihaip/infinite-mac#201]
Can you add a way to add a custom floppy image similar to how you can add a custom CD-ROM image?

**Comment by that-ben** [comment]
Can you elaborate please? e.g. this is a 1.4MB floppy disk image and it can be attached arbitrarily to Infinite Mac: https://infinitemac.org/run?infinite_hd=true&disk=System%207.5.3&cdrom=https://emulate-in-browser.macintoshrepository.org/d/7140_MacSki.dsk

**Comment by upintheairsheep** [comment]
> Can you elaborate please? e.g. this is a 1.4MB floppy disk image and it can be attached arbitrarily to Infinite Mac: https://infinitemac.org/run?infinite_hd=true&disk=System%207.5.3&cdrom=https://emulate-in-browser.macintoshrepository.org/d/7140_MacSki.dsk

Nevermind
