### ISSUE TITLE
"Infinite HD could not be opened" error when IM drive is not attached?

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#202]
Could the "Infinite HD could not be opened" error be avoided when we launch Infinite Mac without the Infinite HD drive attached? I know it does that because it tries to open the Infinite HD drive window in the Finder at startup.  Instead of doing this, could the Infinite HD simply have a couple of aliases of the various useful folders on the desktop so that when you launch IM with the Infinite HD attached, they show on the desktop and when you don't attach Infinite HD, then they simply don't show and there's no file not found error?

![infinite hd not found](https://github.com/mihaip/infinite-mac/assets/13210399/eef73f74-4852-46f7-b482-303dc5cd7f3f)

![asddas](https://github.com/mihaip/infinite-mac/assets/13210399/8577c5fa-3c50-4c0f-b0a9-3e0d78e4c463)

**Comment by mihaip** [comment]
There's not much I can do here, without giving up having the Infinite HD window open.

You can create a custom boot disk that omits that startup item?

**Comment by that-ben** [comment]
Can I make a small 400KB app that you could put in STARTUP ITEMS instead of the Infinite Mac alias? All the app will do is check if Infinite Mac volume exists and if it does, open it, or else do nothing and quit, which will avoid any kind of error popup.  I will send you both the compiled app and the full source code (just a couple lines of code!)

**Comment by mihaip** [comment]
Coming back to this - it turns out the alias is not necessary. There is HFS metadata for storing which window to open when the disk is mounted, it's just that the `machfs` library loses it when building the disk. I'll look into fixing that and then I can remove the alias.
