### ISSUE TITLE
Allow custom amount of RAM

### ISSUE THREAD

**Issue by Iritscen** [mihaip/infinite-mac#203]
Now that we have a build-your-own-Mac feature, can the amount of RAM be customizable too?  Currently an OS 9 Mac is given 128 MB of RAM, but some apps require more than that, especially some of the games that are now available to run on it via the CD Library.  For instance, the Deus Ex demo wants 154 MB of RAM (and yes, Deus Ex does run in SheepShaver because it drops into the software renderer).  Maybe giving a Mac _less_ RAM will also be desirable in some cases, e.g. if that's the solution to #39.

**Comment by that-ben** [comment]
I would have thought it would be as simple as editing the prefs file...
![ramsize](https://github.com/mihaip/infinite-mac/assets/13210399/c199bcfe-7226-4948-a84e-3b6c11efbc07)


... but upon doubling the RAM amount (256MB instead of 128MB) I was greeted with this error:
![adsdasdas](https://github.com/mihaip/infinite-mac/assets/13210399/69551655-2fda-461d-9647-ddba849a046c)


With the Windows build of SheepShaver, it would have worked, but in this WASM build, perhaps it's rooted deeper and/or baked in the compiled program.

**Comment by mihaip** [comment]
Making the RAM size be customizable is a good idea. As of right now I'm using a fixed Emscripten heap size (256 MB for [Basilisk II](https://github.com/mihaip/macemu/blob/49787f862b1941a32c0a80077e1ecededdce5b06/BasiliskII/src/Unix/Makefile.in#L35) and [SheepShaver](https://github.com/mihaip/macemu/blob/49787f862b1941a32c0a80077e1ecededdce5b06/SheepShaver/src/Unix/Makefile.in#L89), 32M MB for [Mini vMac](https://github.com/mihaip/minivmac/blob/565c1719404d483bb1c499b7f6c180e79a1427b6/setup/WRBGCFLS.i#L403))

There a way to allow growth beyond the initial size, but there are [some gotchas](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html?highlight=sallow_memory_growth#access-memory-from-javascript).

**Comment by that-ben** [comment]
If you've set the heap size to 256MB for SheepShaver, then why are we only seeing 128MB in? https://infinitemac.org/2000/Mac%20OS%209.0.4

**Comment by mihaip** [comment]
The heap size is for the entire emulator instance, which needs additional RAM for the screen buffer and any other data structures that it might need, so not all of it is available as RAM for the emulated Mac (but you can get pretty close, e.g. 224MB does work).

**Comment by that-ben** [comment]
Oh I see!

**Comment by mihaip** [comment]
This is now available (and I bumped up the heap size on the Emscripten side so that 256MB is possible, and made it the default for SheepShaver-based instances).
