### ISSUE TITLE
Noooooo! I was winning god damnit! XD

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#208]
Noooooo! I was winning god damnit! XD

![dasdasdas](https://github.com/mihaip/infinite-mac/assets/13210399/f138cb16-ef79-4169-8e90-0b54752023c0)

![dasadsdas](https://github.com/mihaip/infinite-mac/assets/13210399/97a11898-bfbb-42cd-b022-a968d20f9556)

**Comment by mihaip** [comment]
Seems like a pretty accurate recreation of the experience of using a Mac in the 90s. Save early and save often.
