### ISSUE TITLE
Add MacMania disc '1a' to CD-ROM list

### ISSUE THREAD

**Issue by BiggerJ** [mihaip/infinite-mac#210]
It can be found here - https://archive.org/details/MacintoshMania1 - it has completely different contents to the other MacMania 1. Its readme file reveals that it's from 1995.

**Comment by that-ben** [comment]
This is CD 1 of 6 from the Macintosh Mania from the Dutch company Haarlems Uitgeef Bedrijf B.V.  What "other MacMania 1" CD are you referring to?

**Comment by BiggerJ** [comment]
Sorry, I didn't check disk 2. The one with the half-beige label is one I have a copy of, and I was unfamiliar with the others. You can mark this as closed.
