### ISSUE TITLE
Use era-appropriate fonts

### ISSUE THREAD

**Issue by mihaip** [mihaip/infinite-mac#211]
It would be nice to use Geneva and Chicago or Charcoal in dialogs. https://www.hypertalking.com/ has nice bitmap versions of Geneva and Chicago (with anti-aliasing disabled), based on https://32by32.com/'s WordPress theme.

https://os9.ca/ uses Charcoal.

Additional resources:
- http://www.ateijelo.com/blog/2016/09/13/making-an-msx-font
- https://github.com/JohnDDuncanIII/macfonts
- https://tinkerdifferent.com/resources/collection-of-classic-apple-fonts-for-your-modern-computer.130/
- https://fontstruct.com/fontstructions/show/455928/bmpgeneva12

**Comment by that-ben** [comment]
What about using a simple CSS rule to scale it up to like 125% ? Something like
```
.ScreenFrame-Bezel-Beige * {
	font-size: 120%;
}
```

**Comment by mihaip** [comment]
That would end up looking strangely pixelated (at least the versions of Chicago and Geneva that I've found online are only available at size 12).

**Comment by that-ben** [comment]
Are you sure? Modern browsers can use font smoothing when scaling to a non-existent font size.

**Comment by mihaip** [comment]
But the original Mac fonts were not anti-aliased, and part of the idea here is to use the bitmap Chicago 12, etc. fonts.

Chrome and Safari give some control over anti-aliasing, and things look acceptable even when scaled up a bit (though the Geneva in the body is not great)

![Screenshot 2024-04-11 at 21 25 01@2x](https://github.com/mihaip/infinite-mac/assets/513813/96a37214-61de-496d-9449-e22e02f3e59a)

But Firefox does not, and things look both blocky and blurry:

![Screenshot 2024-04-11 at 21 26 25@2x](https://github.com/mihaip/infinite-mac/assets/513813/a968fda5-2762-405d-9579-0551d6e7a8c7)

(may need to view originals on those images, if GitHub is scaling them)

**Comment by mihaip** [comment]
A bit better luck with using ChicagoFLF and other non-bitmap versions though -- it's not quite era-appropriate, but it's more flexible:

![Screenshot 2024-04-11 at 22 22 04@2x](https://github.com/mihaip/infinite-mac/assets/513813/cf6bf642-0881-4028-a3ef-664670e8f6e1)
![Screenshot 2024-04-11 at 22 22 50@2x](https://github.com/mihaip/infinite-mac/assets/513813/dce0f178-d20b-4586-9d8e-c5e3ae665fa9)
