### ISSUE TITLE
Error when choosing shutdown in KanjiTalk7 instance 

### ISSUE THREAD

**Issue by gingerbeardman** [mihaip/infinite-mac#212]
1. https://kanjitalk7.app
2. Choose shutdown (rightmost menu, bottom item)

```
**Emulator Error**
The emulator encountered an error:
RuntimeError: Unreachable code should not be executed (evaluating 'r(t,n)')
```

- I am using [Flotato](https://flotato.com) as a site specific browser to run KanjiTalk7 URL. Mostly as it prevents me accidentally closing/quitting with Cmd+W/Q.

**Comment by mihaip** [comment]
This affected all emulators, should be fixed now (the site returns to the home screen when an emulated Mac is shut down).
