### ISSUE TITLE
Is a similar project planned for other brands?

### ISSUE THREAD

**Issue by upintheairsheep** [mihaip/infinite-mac#214]
I know InfiniteMac is only for Apple products, but in the future, will you make another site for Windows and other operating systems, or will you add other brands to infinite mac?

**Comment by mihaip** [comment]
No, I'm not planning on doing this for non-Apple operating systems. There are other projects that do this for Windows (e.g. https://www.pcjs.org/) or Linux (https://bellard.org/jslinux/).

**Comment by upintheairsheep** [comment]
> No, I'm not planning on doing this for non-Apple operating systems. There are other projects that do this for Windows (e.g. https://www.pcjs.org/) or Linux (https://bellard.org/jslinux/).

Can you please implement the optical disk streaming functionality, and later, possibly the saved HD from Infinite Mac to Virtual x86, a project which runs any x86 operating system on a web browser. This is immensely important for accomplishing your goal of the site, but for the “other side”.
