### ISSUE TITLE
Bug with mouse control on the Marathon series & more

### ISSUE THREAD

**Issue by MarathonMasaster** [mihaip/infinite-mac#215]
Playing the Marathon series after having come from beating them through on Total Carnage through the ios AlephOne port, I wanted to try it on a cool emulation site where I could play it as if I was sent back to the 90s. However, while the keyboard controls work perfectly fine, and audio and the game are fine too, the only issue I've had was trying to use the mouse & keyboard at the same time. I tried with my pad, however the screen would violently shake and react to the slightest touch. So I pulled out my mouse and lowered the DPI, but that too didn't work. I even tried on another device, this time on a legitimate PC, and the problem persisted. I don't mind playing the game by keyboard only as it may have been how it was meant to be played, but it sorta bums me out. Also, trying to make saves in the game causes the entire website to pull up a pop-up and then crash. Is there any workaround you know where I can save the game whilst keeping the tab open, therefor not losing any saved game progress as I've done with Pathways Into Darkness? And is there something else I can do to get mouse controls working too?

**Comment by mihaip** [comment]
Mouse input appears to be a more general issue in the emulators that the site uses under the hood. See also #57 and posts like https://www.emaculation.com/forum/viewtopic.php?p=22534

**Comment by MarathonMasaster** [comment]
So I ended up doing some research, turns out the in the original version of Marathon, which in this case while emulated, remains like the original unlike the open source AlephOne version. The mouse controls for Marathon (1994) would only be able to be used looking straight up and straight down with the ability to shoot. So all you do is remove the need for the look up and look down keys, but now you have to bunch everything else on the left side of the keyboard for mouse controls. Marathon 2 and Infinity fixed this better apparently.
