### ISSUE TITLE
Battle Chess won’t run

### ISSUE THREAD

**Issue by mihaip** [mihaip/infinite-mac#22]

**Comment by mihaip** [comment]
Reducing the RAM give to the Mac to 16MB makes it launch, but that seems too low (even lowering it to 24 is not enough).

**Comment by mihaip** [comment]
Reducing the RAM give to the Mac to 16MB makes it launch, but seems like too low a default (even lowering it to 24 is not enough).

**Comment by Sgeo** [comment]
The Battle Chess documentation suggests changing to 24-bit addressing, but that setting doesn't seem to persist.

**Comment by mihaip** [comment]
Adding support for using mini vMac as the emulation engine (#71) may help, it simulates an old enough Mac that 24-bit addressing should work.

**Comment by mihaip** [comment]
I've now done enough of the Mini vMac/System 6 bringup to try this, and it seems to work (live at https://system6.app):

<img width="762" alt="image" src="https://user-images.githubusercontent.com/513813/213375245-257a35a5-582d-4e50-b484-3d6e2cd725b5.png">
