### ISSUE TITLE
Help wanted with playing A-10 Attack! 1.5

### ISSUE THREAD

**Issue by MarathonMasaster** [mihaip/infinite-mac#221]
Having some trouble with the controls from map to game window when accessing the tutorial missions, can someone provide a list of controls for KBM and Keyboard Only?

**Comment by jcgraybill** [comment]
There's a README.txt for A-10 Attack! available here, with key bindings: https://www.classicmacdemos.com/a-10-attack

**Comment by mihaip** [comment]
Thanks @jcgraybill!

**Comment by MarathonMasaster** [comment]
Thank you so much @jcgraybill !
