### ISSUE TITLE
Mac OS X 

### ISSUE THREAD

**Issue by Monkeyboyzero** [mihaip/infinite-mac#222]
I know that might a little hard to do but if you could the PowerBook g3 can run Mac OS X cheata all the way to panther. The emulation scene has be quite for Mac OS X if you could would be awesome.

**Comment by mihaip** [comment]
Mac OS X requires porting a new emulator, either QEMU (#72) or perhaps DingusPPC (#219). I am researching both of those options, you can subscribe to those issue if I'm able to make progress.
