### ISSUE TITLE
Investigate Virtual x86

### ISSUE THREAD

**Issue by upintheairsheep** [mihaip/infinite-mac#227]
https://github.com/copy/v86
https://github.com/copy/v86/issues/762

**Comment by upintheairsheep** [comment]
Also investigate Halfix https://github.com/nepx/halfix

**Comment by mihaip** [comment]
The project is focused on classic Mac emulation, this is beyond that scope.

**Comment by upintheairsheep** [comment]
It’s exclusively for a Hackintosh disk running early Mac OS X, not for anything else. It’s essentially a “just-in-case” if you fail to bring QEMU.Sent from my iPhoneOn Sep 13, 2023, at 9:43 PM, Mihai Parparita ***@***.***> wrote:﻿
The project is focused on classic Mac emulation, this is beyond that scope.
