### ISSUE TITLE
Trouble with Marathon Netgame setups

### ISSUE THREAD

**Issue by MarathonMasaster** [mihaip/infinite-mac#228]
Tried many times to set up a local netgame on Marathon with other laptops in very close proximity, I dont know whats causing the problem, unless its simply impossible to do because of the port of Marathon. Help?

**Comment by mihaip** [comment]
The workflow from [my demo video](https://www.youtube.com/watch?v=cPu7o6F_lwk) still works (e.g. if I open https://infinitemac.org/1992/System%207.1?appleTalk=marathon_test in two tabs and launch Marathon 1 to host/join).

More details (e.g. does it list the peer in the status display in the bottom right) would be needed

<img width="389" alt="image" src="https://github.com/mihaip/infinite-mac/assets/513813/2162ee30-28bd-4c71-81aa-eb18ce86b2f0">

**Comment by mihaip** [comment]
Closing due to lack of details.
