### ISSUE TITLE
Where is the "Downloads Folder" in these emulators?

### ISSUE THREAD

**Issue by kevinabraun** [mihaip/infinite-mac#236]
Hello! Thank you for making this. I am trying to run the classic game "Ogre" from origin systems. I found the 400k and 800k disk versions. When I drag and drop either one onto any of the emulators on your site the "Copy to Mac" says. the file will be added to the downloads folder. But I cannot find the downloads folder.

Many thanks.

K

**Comment by bshep** [comment]
On the desktop there is an item called 'Outside World' open that and you will find the 'Downloads' folder.

**Comment by that-ben** [comment]
When you drag and drop a disk image onto Infinite Mac, it will mount as a virtual floppy disk drive (or a CD-ROM drive) so you should see it in the right-most column of icons on the desktop already.  If you dragged a .sit or .zip or .hqx file then it will be under "The Outside World" icon on the desktop > "Downloads"

**Comment by kevinabraun** [comment]
![1](https://github.com/mihaip/infinite-mac/assets/12178816/6b58a907-82a0-4529-ba63-dbff13c3097b)
![2](https://github.com/mihaip/infinite-mac/assets/12178816/49087d5d-f852-4a29-ad9e-aa07a2fff487)

Thank you guys but for example, sorry for taking your time. Here's what I see when IO run it via current safari:

**Comment by that-ben** [comment]
Try to rename the file from OGRE.image to OGRE.dsk and then drag and drop it onto Mini vMac, er I mean Infinite Mac :)

**Comment by kevinabraun** [comment]
Of course what you said works as you show AND you are correct about booting from it it seems, but the archive disks I found are "locked" so cannot be booted from. LOL.

**Comment by that-ben** [comment]
The fact that the disk images are locked should not mean that you cannot boot from them at all.  It's unrelated.

**Comment by kevinabraun** [comment]
Granted I am new to all this, but:
![Screenshot 2023-09-24 at 12 33 03 PM](https://github.com/mihaip/infinite-mac/assets/12178816/2e7cbaa1-5901-43ab-b410-412491fdcf97)

**Comment by that-ben** [comment]
I'm not sure how you got that error to show up, but either way, the fact that the disk is locked should not impact if it's bootable or not.  It's completely unrelated.

**Comment by mihaip** [comment]
Note that "The Outside World" only shows up for Basilisk II and SheepShaver-based machines (Mac IIfx, Quadra 650, and the Power Macs). Anything older uses Mini vMac, which can only mount disk images (as you've discovered).

Will look into making the "Copy to Mac" overlay that appears handle that distinction.

**Comment by kevinabraun** [comment]
![Screenshot 2023-09-24 at 12 42 59 PM](https://github.com/mihaip/infinite-mac/assets/12178816/88649e05-e261-449d-80c7-d5427f565091)
This is all I am doing:

**Comment by that-ben** [comment]
Ah, I see, thanks for the clarification on how you got that error.

**Comment by kevinabraun** [comment]
Thanks for your help, I am getting further, but the Ogre app crashes prompting a machine restart. I dont want to take more of your guys time.

**Comment by mihaip** [comment]
Based on the discussion in https://macintoshgarden.org/games/ogre and https://macintoshgarden.org/forum/ogre-origin-systems-1986 it seems that Mini vMac cannot run Orge (Infinite Mac uses Mini vMac for emulation of older systems). I don't think there's much that can be done here.

Will still make the drag-and-drop instructions more clear for older systems.
