### ISSUE TITLE
Empty preset disk

### ISSUE THREAD

**Issue by ghost** [mihaip/infinite-mac#241]
It would be nice to have a preset disk for the Custom machine that is totally empty, so that somebody who selects it could use one of the System Software CD-ROMs to install their own software

**Comment by that-ben** [comment]
Isn't what Saved HD for?

**Comment by lg0735** [comment]
That's for saving the data across machines. I'm talking about a disk that doesn't get saved, and a page reload erases it.

**Comment by that-ben** [comment]
But even if it's persistent, what would prevent you from using it to achieve your goal?
