### ISSUE TITLE
more disk space

### ISSUE THREAD

**Issue by minefox199** [mihaip/infinite-mac#242]
is there a way to have more disk space for the main macintosh hd it self?

**Comment by robinhood2014** [comment]
On a related note, I attempted to drag-and-drop a "Biggy30" -- i.e. a 30GB hard disk image onto an emulated Mac -- only to have the page crash. Perhaps the emulator thought I was trying to _upload_ the image rather than _mount_ it?

**Comment by that-ben** [comment]
Hi Brandon, long time no see!
Please Mihai, correct me if I'm wrong, but to my understanding, the whole file is uploaded in RAM before it's fed to the emulator, therefore, unless you have like 48GB of RAM, I don't think you could use a 30GB disk image.  Again, please correct me if I'm wrong here.

**Comment by mihaip** [comment]
@that-ben that's right, it used to be the case that entire uploaded disk was read into memory. I just fixed that with https://github.com/mihaip/infinite-mac/commit/1446e2837a58c66e7453d989c37c2d0fd5578220, so @robinhood2014 if you want to try again it should work.

@minefox199 the Macintosh HD is meant to be big enough to hold the operating system. Saved HD and imported disk images are the way to get more disk space.
