### ISSUE TITLE
System 1.0 - Clean image

### ISSUE THREAD

**Issue by lg0735** [mihaip/infinite-mac#244]
So I was browsing through the July 1990 dev CD, and found this:
![Capture](https://github.com/mihaip/infinite-mac/assets/143122614/e63ad134-0fd5-4a74-9df6-c01ba3699248)

Now as far as I know, this is a clean image, not modified and then undone like the current one.

**Comment by that-ben** [comment]
Wasn't there a bug with the Chicago font on this one or am I thinking of the wrong one?

**Comment by lg0735** [comment]
I have no idea, as I have no way of cloning this disk image right now. Infinite Mac does not let me make an empty floppy disk, attach it to the emulated machine, and then save the changes to it so I can eject it and put it in the 128K machine. In around 3-4 hours I will have access to a machine with native builds of emulators so I can test it then.

**Comment by mihaip** [comment]
Thanks for filing this, but System 1.0 on that series of developer CDs is actually System 3.2/Finder 5.3. This blog post describes what the other disk images map to (e.g. 0.1 is actually 1.1): https://sandro.knot.org/2014/06/05/seeking-system-0-97/
