### ISSUE TITLE
Kanji Talk 7.5.3 (Power PC) is now available in English

### ISSUE THREAD

**Issue by sabanusi2000** [mihaip/infinite-mac#246]
I'm Japanese and when I opened your Kanji Talk 7.5.3 (Power PC), mac7.53 (Power PC) started.
Also, please add other kanji talks
your project is great

**Comment by mihaip** [comment]
There is no PowerPC version of KanjiTalk, the only version is a 68K install: https://infinitemac.org/1996/KanjiTalk%207.5.3. Did you mean something else?

Is there a specific version of KanjiTalk you're interested in? #131 is about adding the System 6 version, and #206 is somewhat related (for adding more Japanese software, which may need more OS versions).

**Comment by gingerbeardman** [comment]
Without a Power PC install of Japanese Mac OS there is another way to do it: Installing Language Kits

- https://github.com/mihaip/infinite-mac/issues/105
- https://blog.gingerbeardman.com/2023/11/07/japanese-lanuage-support-on-classic-macintosh/

**Comment by mihaip** [comment]
Thanks for the details @gingerbeardman. I'm closing this in favor of #105 and #251, which capture the intent more specifically.

**Comment by gingerbeardman** [comment]
I also wonder if there is a PPC version of Japanese Mac OS. One actually never looked for one because I mostly just System 7 on a 68000.

**Comment by Okokeee** [comment]
Ok
