### ISSUE TITLE
Crash opening a folder on Infinite HD

### ISSUE THREAD

**Issue by jcs** [mihaip/infinite-mac#247]
1. Navigate to https://infinitemac.org/1990/System%206.0.5?saved_hd=false in a private window.
2. Open Inifinte HD
3. Navigate to Developer -> THINK Pascal
4. Open THINK Pascal 4.0 Utilities folder, and the VM will crash

**Comment by that-ben** [comment]
This happens because something in the Desktop DB is incompatible with System 6.  You can just hold down the OPTION (ALT) key upon boot and keep it held down until it reaches the desktop and asks you to rebuild the desktop.  Rebuild also Infinite HD which is where the incompatibility occurs.  Then it works just fine:
![dasdas](https://github.com/mihaip/infinite-mac/assets/13210399/e68af9ad-1e9b-4c0e-a875-4ae8de382951)

**Comment by mihaip** [comment]
I do rebuild the desktop DB with both for precisely this reason: https://github.com/mihaip/infinite-mac/blob/09244dcec7e37b51e74ecae85f6d93aba4860435/scripts/import-disks.py#L583-L597

Is there a difference between an explicit desktop DB rebuild (when command-option is held down) vs an automatic one (which is what I rely on -- the generated disks don't have a Desktop file at all, so the Finder creates one when the disk is mounted)?

**Comment by that-ben** [comment]
There shouldn't be any difference between a missing Desktop DB (or "Desktop" under System 6) that's automatically regenerated upon boot vs when you hold down COMMAND-OPTION on boot to manually trigger the Desktop DB regeneration.  The question is what happened on that IM release? Was it incorrectly generated? Was the THINK Pascal folder added after the desktop was automatically built and the Finder did not like something in that folder which prevented it to add it to the Desktop DB?

So if I understand correctly, the code above is run before you release IM and Desktop DB never exists before you run that code, correct? Are you sure the "Desktop" file (for System 6) also does not already exist when you run this code?

**Comment by mihaip** [comment]
I ended up generating a smaller version of Infinite HD for System 6 and earlier (which excludes software that's too new to run on it), and that allows this folder to open.

**Comment by that-ben** [comment]
This makes more sense anyway, good call! Thanks :)
