### ISSUE TITLE
add system software 1 betas

### ISSUE THREAD

**Issue by thewanderingtraderm** [mihaip/infinite-mac#250]
you should add system software 1 betas. Here is the download link: http://toastytech.com/guis/Apple%20MacOS%20Pre-Releases.zip

**Comment by mihaip** [comment]
Thanks for the suggestion. I'm currently focused on stable/official OS releases only.

**Comment by that-ben** [comment]
<img width="488" alt="Screenshot 2023-11-16 at 9 59 09 AM" src="https://github.com/mihaip/infinite-mac/assets/13210399/92b209fd-8cf0-4589-a6f6-803521fc8e56">

**Comment by thewanderingtraderm** [comment]
its a false positive
