### ISSUE TITLE
Unable to find application named 'Mini vMac'

### ISSUE THREAD

**Issue by ChiefBreakeverything** [mihaip/infinite-mac#253]
Hey there, so excited to try this out since I was raised on System 6/7 Macs! I'm currently on Ventura 13.5.1

I've pulled the submodules successfully, ran build-xadmaster, but then when I run import-disks.py I get:

Building System 6 Desktop for Infinite HD6.dsk...
Unable to find application named 'Mini vMac'
Traceback (most recent call last):
  File "/infinite-mac/scripts/import-disks.py", line 695, in <module>
    build_desktop_db6([infinite_hd6_image])
  File "/infinite-mac/scripts/import-disks.py", line 603, in build_desktop_db6
    minivmac.run([disks.SYSTEM_608.path()] + [i.path for i in images])
  File "/infinite-mac/scripts/minivmac.py", line 9, in run
    subprocess.check_call([
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['open', '-a', 'Mini vMac', '-W', '--args', '/infinite-mac/scripts/../src/Data/Mac-Plus.rom', '/infinite-mac/scripts/../Images/System 6.0.8 HD.dsk', '/var/folders/kx/7pv7w7_n4jv2b22rlmg0s0xm0000gn/T/tmpgqbfoyd1/Infinite HD6.dsk']' returned non-zero exit status 1.

It _sounds_ like Mini vMac is missing, even though the submodule is populated. I tried fetching the latest stable build for Silicon in case thats required too, but I get a "Mini vMac is damaged and can't be opened. You should move it to the bin." error when I try to open it.

**Comment by mihaip** [comment]
Building the Infinite HD disk image uses the native build of Mini vMac (and Basilisk II) to ensure that the Desktop DB is built. I'll see about making it fail more gracefully if it's missing, but in the meantime you can run the command using something like 

```
DEBUG_SYSTEM_FILTER=7.5.3 npm run import-disks
DEBUG_LIBRARY_FILTER=MacWrite npm run import-disks
```

That will build just one OS image (change 7.5.3 to whatever you're looking to run) and a subset of the Infinite HD software (and skip the desktop rebuild).

**Comment by mihaip** [comment]
With https://github.com/mihaip/infinite-mac/commit/74356471272821329d5eb25c00413d7348a66750, the `import-disks` script should continue even if the native binaries can't be found.
