### ISSUE TITLE
Trouble running the CD ROMS from the tab bellow, and Myth: The Fallen Lords

### ISSUE THREAD

**Issue by MarathonMasaster** [mihaip/infinite-mac#254]
I keep getting errors when trying to run Myth: The Fallen Lords, and getting a very long string of error code when trying to run other ROMS.
What would be the steps for running ROMs and putting them into the emulator too, does it involve messing with file moving or dowloading?

**Comment by mihaip** [comment]
The Myth CD-ROM is being loaded from https://archive.org/details/Myth_The_Fallen_Lords_Bungie_1997/. It's possible that archive.org is having issues. You can also download the .iso file from there and then drag it into the simulator window to mount it.

**Comment by MarathonMasaster** [comment]
I tried doing that, but it only seemed to work less, I get to the main menu, then upon trying to load up a level, the game just breaks and I get some error code on screen.
