### ISSUE TITLE
Build Question: Can I build this without xcode (to build on linux or windows?)

### ISSUE THREAD

**Issue by qtqgyt** [mihaip/infinite-mac#258]
I think my title explains it pretty well. If you need more information, please contact me.

**Comment by mihaip** [comment]
I believe everything important should work. The `npm run build-xadmaster` step can be skipped (it builds using Xcode) and the disk importing process will skip over archives that need to be decompressed.

**Comment by qtqgyt** [comment]
> I believe everything important should work. The `npm run build-xadmaster` step can be skipped (it builds using Xcode) and the disk importing process will skip over archives that need to be decompressed.

Thanks! I just asked because last time it was complaining about not being able to find the Data directory.
