### ISSUE TITLE
Locally Built copy missing "The Outside World"

### ISSUE THREAD

**Issue by qtqgyt** [mihaip/infinite-mac#260]
Again, I hate to be opening pointless issues that probably have a really simple solution, but in my locally built copy, "The Outside World" folder is missing, so I can't upload files to the emulator. Am I just missing something really simple here?

**Comment by mihaip** [comment]
It depends on which emulator/machine you're using. Only Basilisk II and SheepShaver support it, which translates to the Mac IIfx, Quadra 650, Power Mac 9500, and Power Mac G3 (B&W). See https://github.com/mihaip/infinite-mac/blob/main/src/machines.ts for the machine definitions and which emulator is used for each one.

**Comment by qtqgyt** [comment]
Eh I found a workaround, (although the outside world still doesn't exist), but thanks :)

**Comment by qtqgyt** [comment]
extfs /Shared/
seriala
serialb
ether js
bootdrive 0
bootdriver 0
frameskip 0
fpu true
nocdrom false
nosound false
noclipconversion false
nogui true
jit false
jitfpu false
jitdebug false
jitcachesize 8192
jitlazyflush true
jitinline true
keyboardtype 5
keycodes false
mousewheelmode 1
mousewheellines 3
idlewait true
rom Quadra-650.rom
cpu 4
modelid 30
ramsize 134217728
screen win/800/600
disk System 7.5.3 HD
disk Infinite HD
disk Saved HD
cdrom /cdrom/0
cdrom /cdrom/1
cdrom /cdrom/2
cdrom /cdrom/3
cdrom /cdrom/4
cdrom /cdrom/5
cdrom /cdrom/6
jsfrequentreadinput true
