### ISSUE TITLE
Unable to install Mac OS X on Mac OS 9 emulator (Power Mac G3 256MB RAM)

### ISSUE THREAD

**Issue by Bonzey2416** [mihaip/infinite-mac#261]
I am trying to install Mac OS X on the most powerful Mac OS emulator (Power Mac G3 Blue/White with 256MB RAM), but it is failed.

The error is:
> A fatal error occurred.
> “No compatible property in device-tree. (-2539)”

It **should** be able to run Mac OS X as it meets the requirements: PowerPC G3 processor and 256MB RAM

![IMG_0568](https://github.com/mihaip/infinite-mac/assets/98016194/a35c4650-47a4-4cb2-9a9f-ae88185da666)

**Comment by lg0735** [comment]
That emulator uses SheepShaver, which doesn't emulate the MMU. That is required for Mac OS X to run (and anything above 9.0.4). You can actually boot Mac OS X in the G3 Beige experimental emulator but there is no mouse, keyboard, or really anything. It does boot up but dies when attempting to launch the installer (GPU emulation is incomplete most likely)

**Comment by that-ben** [comment]
lol "the most powerful Mac OS emulator"... uhhhhh... no.

**Comment by mihaip** [comment]
Mac OS X requires porting a new emulator, either QEMU (#72) or perhaps DingusPPC (#219). I am researching both of those options, you can subscribe to those issue if I'm able to make progress.
