### ISSUE TITLE
Custom fonts on Mac OS 1 through 9.0.4?

### ISSUE THREAD

**Issue by Bonzey2416** [mihaip/infinite-mac#262]
I transferred Roboto fonts from my computer to Mac OS 9 emulator (Power Mac G3 B/W 256MB RAM) and when I try to open the font, I get an error:
> **The document "Roboto-Regular.ttf" could not be opened, because the application program that created it could not be found.**
> Could not find a translation extension with appropriate translators.

Do I need to install programs to install fonts? What should I do?
![image](https://github.com/mihaip/infinite-mac/assets/98016194/cc79892a-24b6-45e0-ba29-a6006838a563)

**Comment by lg0735** [comment]
You need to drag & drop these fonts into the Fonts folder in the System Folder. Then restart.

**Comment by Bonzey2416** [comment]
Do I need to install programs to convert Roboto font to run on Mac OS?

**Comment by that-ben** [comment]
Where did you get those TTF files exactly? Pinpoint the archive location on the internet (URL) or explain how you came up with those files.  The reason they appear as a blank/unknown file is because they lack their resource fork.  This could be caused by a couple different scenarios, but until you explain where you got the files exactly and all the steps you did with that archive before inner individual TTF files appear in the emulator, it's hard to guess.

**Comment by lg0735** [comment]
I'm guessing they came from [here](https://fonts.google.com/specimen/Roboto), so these fonts obviously don't have a resource fork as they are intended for Windows/Mac OS X/Linux/BSD/whatever, not Classic Mac OS.

**Comment by that-ben** [comment]
What do you mean by you're "guessing" they came from there?

**Comment by lg0735** [comment]
When I tested this, I downloaded the fonts from there, and it was the same problem. I'm not the person who opened the issue, so that could very well not be where they came from, but it looks like the same problem.

**Comment by that-ben** [comment]
lol I'm so sorry! I thought you were the OP, I didn't check carefully... brainf4rt lol ;-)

**Comment by mihaip** [comment]
The Infinite Mac issue tracker isn't really a place for figuring out how to convert modern TrueType fonts to something that classic Mac OS understands (I agree with https://github.com/mihaip/infinite-mac/issues/262#issuecomment-1840999060 about where the fonts likely came from). 

You may better luck on forums such as https://www.emaculation.com/forum/ or https://68kmla.org/.
