### ISSUE TITLE
Add support for uploading a disk image before launching emulator

### ISSUE THREAD

**Issue by lg0735** [mihaip/infinite-mac#265]
So I am trying to test the DingusPPC emulator(s) and the disk chunk load errors are becoming a problem as the emulator craps out when it should not. Unfortunately, since the HDD emulation is not finished, I can't use one of the pre made Mac OS disks. I have to boot from floppy or CD. To me it seems like it would be useful to be able to upload an image and then boot from that image, so there would be no disk chunk load errors getting in the way of booting. I also think it would be useful to boot up the emulator(s) with no disk images attached, for testing reasons (dragging in an image to boot from)

**Comment by that-ben** [comment]
@lg0735 You can feed an invalid disk image to boot from (e.g. System 1.0 paired with PM G3 (Beige) for DingusPPC) which will essentially boot it without a boot disk: https://infinitemac.org/1984/System%201.0?infinite_hd=false&saved_hd=false&machine=Power+Macintosh+G3+%28Beige%29

@mihaip Could we have http://localhost added to the list of whitelisted domain names to attach disk images? This would enable us to use our local disk image files to boot the emulator from (OP's issue would be solved easily with this).

<img width="1197" alt="Screenshot 2023-12-15 at 4 42 03 PM" src="https://github.com/mihaip/infinite-mac/assets/13210399/634975c7-c91a-49b4-ab4e-372638ea4ba7">

**Comment by mihaip** [comment]
This is now implemented: when running a custom instance there is a "Disk File…" option when choosing a disk. .iso files will be mounted a CD-ROMs, which is necessary for DingusPPC  to be able to actually load the 7.1.2 startup image.

@that-ben: loading of files via URL is handled by the Cloudflare Worker, so unfortunately the localhost option won't work -- the worker can't see your local web server.
