### ISSUE TITLE
running osx

### ISSUE THREAD

**Issue by Pierrestro** [mihaip/infinite-mac#266]
why not to try to make osx available also early version of mac os

**Comment by spetterman66** [comment]
The maintainer is busy working on making early Mac OS X versions available to emulate in Infinite Mac.
________________________________
From: Pierrestro ***@***.***>
Sent: Monday, December 18, 2023 3:07 PM
To: mihaip/infinite-mac ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mihaip/infinite-mac] running osx (Issue #266)


why not to try to make osx available also early version of mac os

**Comment by lg0735** [comment]
We've gotten far enough in DingusPPC to show the spinning wheel, and a kernel panic:
<img width="1227" alt="276504149-39988dfd-69b7-48ac-8716-eff2c577c469" src="https://github.com/mihaip/infinite-mac/assets/143122614/abedd72e-20a5-4c57-962b-d1e5726d0afb">
![291309502-dcba76e5-0f4c-4bc0-8e2b-31f472df5fb1](https://github.com/mihaip/infinite-mac/assets/143122614/41a88ad9-b55f-4483-89c9-86e2b3bcef3b)
OpenDarwin 6.6.2 also works, which is essentially MacOS X without the GUI
![291316070-1599df0e-3223-4e7c-b82f-ae965971f01c](https://github.com/mihaip/infinite-mac/assets/143122614/5d67fd06-4f19-4cca-8eac-728565b7bf4d)

Most of the issues seem to be graphics related so once that's figured out it should be possible to actually see the installer.

**Comment by Pierrestro** [comment]
adding qemu to infinite mac would help considering I already did a project like that in the past (it's x86 and not PPC) it's will make osx 10.0 to 10.5 compatible hope that help

**Comment by that-ben** [comment]
> adding qemu to infinite mac would help considering I already did a project like that in the past (it's x86 and not PPC) it's will make osx 10.0 to 10.5 compatible hope that help

It would work, but it would be EXTREMELY slow.

**Comment by Pierrestro** [comment]
> > adding qemu to infinite mac would help considering I already did a project like that in the past (it's x86 and not PPC) it's will make osx 10.0 to 10.5 compatible hope that help
> 
> It would work, but it would be EXTREMELY slow.

it will depends on real machine speed it's not the fault of qemu if this will be slow but fault to the real machine
