### ISSUE TITLE
Buggy scripts somewhere in site (or JIT failing?)

### ISSUE THREAD

**Issue by ghost** [mihaip/infinite-mac#268]
For whatever reason, Infinite Mac will sometimes begin to rapidly leak RAM. After about a minute, this was the RAM usage
![image](https://github.com/mihaip/infinite-mac/assets/143122614/fbd92921-fb72-46dd-af2b-21751521fe6a)
(10.5 GB!!)

This only happens on Infinite Mac. I think it is emulator related since this only happens after I run an emulator.

**Comment by mihaip** [comment]
Can you provide some more details: Does this happen for all emulators? As soon as launched or after a while? Does it persist if close the emulator? What does the Chrome task manager (which has per-site details) show? 

Even in this screenshot, could you not crop it so aggressively -- I can't see the units for the "10,504.8…" column or what the header is.

**Comment by lg0735** [comment]
Alright, so after 20 minutes of using Infinite Mac, I received this error when shutting down SheepShaver (running Mac OS 8.5)
![image](https://github.com/mihaip/infinite-mac/assets/143122614/d85a5f24-99e7-4258-b894-fa64eb418e63)

Checked the Chrome Task Manager after hitting "home", and...
![image](https://github.com/mihaip/infinite-mac/assets/143122614/7e234564-c864-450e-af1a-ebcaccd1c177)

In more extreme cases Chrome itself would freeze, but the picture above was taken with NO emulator running.

**Comment by lg0735** [comment]
> 1GB is a lot but it's not shockingly huge... Nothing compared to the 10GB in the top post. Though, 1GB is a lot for a somewhat small HTML page with no emulator loaded, that's true. There must be a memleak in the SheepShaver.js emulator.
> 
> I repeated your experience with Firefox under W7 and it's true that if you use the emulator and crash it (I launched Battle Chess under Mac OS 9.0.4) the RAM is left completely garbage uncollected. I was at 430MB when SheepShaver.js crashed and upon clicking "Home", it was at 445MB and it remained like that after the page was loaded. After reloading the page, it only used 51MB of RAM.
> 
> In hindsight, I think it's normal for your tab to continue to use 1GB after you click "Home" because it does not reload the page, it only shows the InfiniteMac.org page on top of the emulator you were using, but the emulator is not garbage collected from the browser. If you refresh the page after using the emulator, your RAM usage will fall to 50MB-ish.

The weirdest thing was when I was using System 7.1.1 and moving some files and suddenly Chrome froze, so I opened the task manager and saw it rapidly eating RAM and using 100% CPU. That's when I took the cropped picture in the first post.
