### ISSUE TITLE
CD-ROM "could not load disk chunk" errors

### ISSUE THREAD

**Issue by gingerbeardman** [mihaip/infinite-mac#269]
- Chrome
- Mac OS 8.5
- PanicDisc and others

After the errors the disc / folder I am opening does appear.

![Screen shot 2023-12-21 at 23 24 51](https://github.com/mihaip/infinite-mac/assets/49612/9dd18de6-4443-43d3-8058-d17d4cf4bfd7)

![Screen shot 2023-12-21 at 23 26 39](https://github.com/mihaip/infinite-mac/assets/49612/cf9a6c08-0a0c-4719-92e8-85ae40212edc)

![Screen shot 2023-12-21 at 23 27 23](https://github.com/mihaip/infinite-mac/assets/49612/67181280-fe16-48a1-b1f5-08dbe26be5d6)

![Screen shot 2023-12-21 at 23 32 48](https://github.com/mihaip/infinite-mac/assets/49612/2b43ead7-13dc-4611-b3cf-19595e0a94c6)

**Comment by mihaip** [comment]
These are all from the archive.org servers, I'm not sure there's much I can do there (without getting into the business of hosting my own copies).

**Comment by gingerbeardman** [comment]
Good to know, thanks!
