### ISSUE TITLE
Mini vMac with full DC42 support 

### ISSUE THREAD

**Issue by Lucas-mother3** [mihaip/infinite-mac#270]
So I have these clean disk images of Macintosh System Software version 0.97 (as part of a research into the topic) as well as the MacWrite/MacPaint disk.

In MacPaint 1.0, the application would complain about a disk error shown here:
![IMG20231204081226](https://github.com/mihaip/infinite-mac/assets/76678069/67516d77-d15c-4581-b742-d62ee1f7cd2b)

This is on a school computer running Mini vMac 128k but it has the same error in the website. It seems like this is the default behavior under normal builds of Mini vMac (since by default, it would partially support the disk image format). A fix for that is to append `-sony-tag 1 -sony-sum 1 -sony-dc42 1` to the builder script, which fixes the problem. This also inadvertently adds support for the Sony Test disks, which are beta versions of the Macintosh System Software. 

Since the aim of the project is to run Macintosh software anywhere, adding full support for the Disk Copy 4.2 image format improves the compatibility of such software.

**Comment by mihaip** [comment]
Thanks for flagging this, I've added those build flags and rebuilt the versions.
