### ISSUE TITLE
System 1.0 - Clean Disk Image, take 2

### ISSUE THREAD

**Issue by lg0735** [mihaip/infinite-mac#271]
Thanks to @Lucas-mother3's issue filed here I found a gist (https://gist.github.com/Lucas-mother3/3f47b1241232e1810bbc80f07323139e) on their profile and there was a link to dumps of various copies of System 0.97.

One of them (https://www.earlymacintosh.org/disk_images.html#System_1) was dumped from disks that _were still in their original boxes_ **and** untouched. For some reason Windows Explorer struggles with the ZIP archive so I had to use 7-Zip to get them out.

This is what they look like in Infinite Mac.
![image](https://github.com/mihaip/infinite-mac/assets/143122614/e51bef9e-b2fd-475a-9dec-e4740b9ae493)
![image](https://github.com/mihaip/infinite-mac/assets/143122614/008b8ec6-f759-4791-aed3-45cd70072ba0)
![image](https://github.com/mihaip/infinite-mac/assets/143122614/aa33b52e-b901-4dd2-88e1-b7dbad4faf67)
![image](https://github.com/mihaip/infinite-mac/assets/143122614/2b59f8b3-e6dc-4e02-affd-b8c7f7a88c5e)

MacPaint errors out but this seems to be the same issue as #270 so once that's fixed this should work.
![image](https://github.com/mihaip/infinite-mac/assets/143122614/21664ed0-8d6b-4073-9928-e5c820e55160)

Due to various quirks in this disk image vs the one in Infinite Mac, I believe that we don't actually have 0.97 in Infinite Mac yet.

**Comment by mihaip** [comment]
Thanks for bringing this to my attention, I wasn't ware of @Lucas-mother3's research or the https://www.earlymacintosh.org/disk_images.html#System_1 archive.

I redid the System 1.0 to be based on that. If you want a truly "pristine" experience (which no "Welcome" document or any other additions), I also added the original System Disk as a separate boot floppy: https://infinitemac.org/run?disk=System+1.0+%28System+Disk%29 (you can access it from the "Disk" drop down in a custom instance).
