### ISSUE TITLE
Investigate Shoebill 

### ISSUE THREAD

**Issue by Lucas-mother3** [mihaip/infinite-mac#274]
So I was thinking about adding A/UX to the mix of classic Mac System Software into Infinite Mac because I think it's a peculiar piece of software in the history of Apple. A/UX combines the Mac GUI with a Unix system, years before Mac OS X (altough both systems are incompatible with each, as A/UX runs a different Unix base than OS X.) It could be run on specific models (models with MMUs mostly, but iirc it could be run on select Macintoshes of the era). 

While QEMU has support for a Quadra 800 machine to run A/UX 3.0, I currently have not found some success running it properly, so I turned into [Shoebill](https://github.com/pruten/shoebill), an emulator that could specifically run any version of A/UX released. The problems right now is that there is no port of the emulator to JS or WASM, and the developer abandoned it due to conflict of interest issues. But I think it's interesting to investigate with the emulator, and see if A/UX could be run properly under Infinite Mac.

**Comment by Lucas-mother3** [comment]
A good way to start is to follow this guide [here](https://www.emaculation.com/forum/viewtopic.php?t=8483) to set up disk images, which needs a separate emulator (apparently) to run the SCSI disk program, then Shoebill for the rest. I think this mostly applies to A/UX 3.0, but it's still possible to run 1.x to 2.x, with some modifications.

**Comment by mihaip** [comment]
It would be interesting to get Shoebill running. This is tracked in #129.
