### ISSUE TITLE
[LIBRARY REQUEST] Apple Mac OS Anthology 

### ISSUE THREAD

**Issue by Lucas-mother3** [mihaip/infinite-mac#276]
I recently found a huge collection of Mac OS installer disks (ranging from System 7.0 to Mac OS X 10.1) called Mac OS Anthology, spanning many DVDs, with international releases to aid with developers.

I wanted to add this to the library as well because it includes possibly clean dumps of Macintosh System Software.

Link: https://macintoshgarden.org/apps/mac-os-anthology-99

**Comment by mihaip** [comment]
Thanks for the suggestion. These should now be present in the CD-ROM library (under "System Software/Compilations").

**Comment by that-ben** [comment]
While DVD #1 works, DVD #2 looks like this for me:

<img width="2035" alt="Screenshot 2023-12-29 at 1 23 29 PM" src="https://github.com/mihaip/infinite-mac/assets/13210399/8e14d1e5-c7e9-4f16-b4ff-8dfede95908b">

**Comment by that-ben** [comment]
They now work, thanks.
