### ISSUE TITLE
Cursor wouldn't respont at bottom half of screen in NeXTSTEP

### ISSUE THREAD

**Issue by Bonzey2416** [mihaip/infinite-mac#278]
I have recently tested NeXTSTEP and it boots fairly well. However, when I tried to move cursor to bottom the cursor didn't respond. Only at the top half it responds.

**Comment by that-ben** [comment]
The fix improved the mouse cursor jumping around a lot but would it be possible to slightly reduce the mouse sensitivity to even further improve it?  BTW, I love the NeXT monitor CSS, it looks good!

**Comment by mihaip** [comment]
@that-ben Yes, it is rather sensitive. Added to #121.
