### ISSUE TITLE
Add Google Fonts to Infinite Mac (System 7 to Mac OS 9.0.4)

### ISSUE THREAD

**Issue by Bonzey2416** [mihaip/infinite-mac#279]
I would like to add Google Fonts to Infinite Mac in ttf.bin format. Currently the default contains only a few fonts eg. Chicago, New York and Geneva.

Here’s a list of Google Fonts to be added to Mac OS in ttf.bin format:

- [ ] Roboto
- [ ] Roboto Mono
- [ ] Roboto Slab
- [ ] Roboto Serif
- [ ] Open Sans
- [ ] Noto Sans
- [ ] Noto Serif
- [ ] Montserrat
- [ ] Nunito
- [ ] Rubik
- [ ] Oswald
- [ ] Source Sans Pro
- [ ] Source Code Pro
- [ ] IBM Plex Sans
- [ ] IBM Plex Serif
- [ ] Arimo
- [ ] Archivo 
- [ ] Oxygen 
- [ ] Ubuntu

I would also love if they created a CD consisting of these fonts.

**Comment by mihaip** [comment]
I'm not able to handle requests for arbitrary content on the disk images. However, you can use the "Outside World" drive to import files, and "Saved HD" to have a persistent place. You can copy an existing System Folder to it, make any modifications, and then boot from it.
