### ISSUE TITLE
Could the following be added to the Infinite Mac "Infinite HD"?

### ISSUE THREAD

**Issue by spetterman66** [mihaip/infinite-mac#280]
OmniWeb for NeXTSTEP, it could fit in the Networking folder.
Several versions are available at https://files.omnigroup.com/software/Archive/NEXTSTEP/OmniWeb/ (yes, they still host it!)

**Comment by mihaip** [comment]
This will require additional changes, since Infinite HD is HFS-based, but NeXTSTEP uses UFS. I'll track this as part of the general NeXT/Previous work in #121.

**Comment by mihaip** [comment]
Incidentally, you can run OmniWeb 1.0 today if mounting a CD-ROM with it, for example in http://localhost:3127/1994/NeXTSTEP%203.3?infinite_hd=false&saved_hd=false&cdrom=https%3A%2F%2Farchive.org%2Fdownload%2FPeanutsNeXTISO%2FPeanuts-1.iso (it's Peanuts 1 -> CDROM -> Basic Apps)

<img width="1248" alt="image" src="https://github.com/mihaip/infinite-mac/assets/513813/f5ade5b7-9829-4dfa-a1b3-e9384b28801f">

**Comment by spetterman66** [comment]
That's a localhost URL 🙂
________________________________

**Comment by mihaip** [comment]
Oops, should be https://infinitemac.org/1994/NeXTSTEP%203.3?infinite_hd=false&saved_hd=false&cdrom=https%3A%2F%2Farchive.org%2Fdownload%2FPeanutsNeXTISO%2FPeanuts-1.iso
