### ISSUE TITLE
Crashing at loading step 4/4 in new browser releases (e.g. FF 122.0) with: Failed to load worker script 0x80530013

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#285]
Hi, we're using a build from last year on MR and it was working fine until today under Firefox 121.0.1 and also on many previous releases.  I just tried it 2 minutes ago on FireFox 121.0.1 and it was loading just fine, but after applying the 122.0 update and restarting, InfiniteMac does not load anymore and hangs at loading step 4/4.  I've confirmed with other users as well.  Also, it does the same under Safari on macOS 14.2.1 and also on iOS Safari on a modern iPhone.  It's working fine under FF 121.0.1 but not under FF 122.0.

Was there a bug fix over the last 8 months that prevented the crash at step 4/4 with this kind of JS error in the console?

`NetworkError: WorkerGlobalScope.importScripts: Failed to load worker script at blob:https://emulate-sheepshaverjs.macintoshrepository.org/cb037672-127c-48a7-a840-efece5e2607a (nsresult = 0x80530013)`

In the error above, if I copy/paste the URL `blob:https://emulate-sheepshaverjs.macintoshrepository.org/cb037672-127c-48a7-a840-efece5e2607a` in my browser, it displays the whole JS file just fine.

<img width="1293" alt="Screenshot 2024-01-30 at 8 25 25 PM" src="https://github.com/mihaip/infinite-mac/assets/13210399/3cc8941c-887f-40c6-afc4-02e74d0f3d77">

**Comment by mihaip** [comment]
I stopped using `importScripts` with https://github.com/mihaip/infinite-mac/commit/b221259595d323d2c45cd2175fdc7ce9287c3097, so I'm guessing you'll want to pick up a build that has that.

**Comment by mihaip** [comment]
> I see, thanks for pointing that out... and was that decision to stop using importScripts based on a possible incompatibility with more modern browsers?

It was a general modernization of the build system, not aimed at fixing issues. The switch away from `importScripts` was a downstream effect, the commit message has the full yak shave history.

> I'm also asking because I'm wondering if the new code you made that replaces importScripts will still work in older Firefox versions that ran under W7

When I implemented it in late May 2023 I tested with the current versions of Safari, Firefox and Chrome. Based on https://wiki.mozilla.org/index.php?title=Release_Management/Calendar&redirect=no that would have been Firefox 112 or 113.

> I lol'ed at your source in index.js "__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED" 🤣

It comes from React, I can't take credit for it.

> I'm serving everything with HTTPS and I even tried to force every single request through .htaccess as HTTPS, but it didn't make a difference.

Not familiar with this error, but https://stackoverflow.com/questions/49539306 has some possible causes (wrong MIME type, third-party cookies being blocked, etc.)

**Comment by that-ben** [comment]
Thanks to an user on MR who posted their screenshot of Chrome, I got a refined error and it became clear that the file RunDefMac-878e86b8.js had a bad definition of the worker scope.  In your file it was: `{scope:"/",type:a}`
...but it should really be: `{scope:"/assets/",type:a}`
Did you force this scope through another file perhaps for this to work on InfiniteMac? Because the error goes away and the worker installs and activates when I set the scope to "/assets/" instead of "/" so perhaps in a .htaccess you forge a header to mimic that?

**Comment by mihaip** [comment]
It's intentional that I use / as the worker scope. There's a corresponding header on the server side (https://github.com/mihaip/infinite-mac/blob/de7553f1a61297c52bb5003dc1623da169ee3c9e/workers-site/index.ts#L87-L90) that enables it.

**Comment by that-ben** [comment]
Oh yeah! I totally overlooked that new header! Thanks for pointing that out! 👍 
Works perfectly when adding that header to the .htaccess file.
PERFECT! Thanks Mihai! Will be sending yet another donation for you next week.

**Comment by mihaip** [comment]
Glad it worked!

**Comment by that-ben** [comment]
Donation sent! THANKS for what you're doing with InfiniteMac!
