### ISSUE TITLE
Verbose Mode for NeXTSTEP?

### ISSUE THREAD

**Issue by upintheairsheep** [mihaip/infinite-mac#287]
Can you have the ability to add the verbosity flag in NeXTSTEP’s advanced options menu as a checkmark, for advanced users who want to see the boot process, or users with slow devices who would like to see the boot process?

**Comment by mihaip** [comment]
This is possible via the `?debug_log=true` query parameter: https://infinitemac.org/1994/NeXTSTEP%203.3?debug_log=true

It's esoteric enough that I'm not planning on adding UI for it.

**Comment by upintheairsheep** [comment]
Thank you.
