### ISSUE TITLE
MacPaint 1.5 on System 7.5 is best somewhat buggy

### ISSUE THREAD

**Issue by drj11** [mihaip/infinite-mac#290]
This is an absolutely amazing project by the way.

Here i have opened MacPaint 1.5 on https://infinitemac.org/1996/System%207.5.3 and scribbled about a bit.

![image](https://github.com/mihaip/infinite-mac/assets/1215412/f8d21079-e9a0-4641-a25a-19f05c1c29ce)

Observations:
- toolbar on left is incorrectly drawn and obliterates some of the menu bar.
- the scribble in the draw area is not drawn there, but appears duplicated in some other part of the screen instead.

That's add. Furthermore, quitting (with File > Quit) produces this. Oh, now it's fine. But when i first encountered it, i got a bomb with Error code 10 and i had to restart the Mac.

**Comment by that-ben** [comment]
That's expected and it would do about the same on real hardware.  I have seen this many times in the late 90's and early 2000's.  You need to run old software in an era appropriate OS, that is a System version that runs in B&W such as System 4.

**Comment by mihaip** [comment]
@that-ben is correct -- MacPaint 1.x is from the era of black-and-white Macs and does not handle more modern machines that well. If you change the screen to black and white (using the control strip in the lower left) it'll mostly work, but running it on an era-appropriate OS/machine is an even better bet.
