### ISSUE TITLE
Virtual trackpad for mobile devices

### ISSUE THREAD

**Issue by robinhood2014** [mihaip/infinite-mac#291]
I'd like to see the addition of a virtual trackpad to facilitate the use of Infinite Mac on iOS and Android devices. Right now the jumping behavior of the emulated mouse cursor is causing some unease of use on these platforms, because the touchscreen's default behavior is to register direct manipulation of screen elements, which doesn't translate well to a classic, non-touchscreen Mac, which expects indirect manipulation and relative positioning.

**Comment by that-ben** [comment]
Alternatively (and although it won't solve everything) you could try the new mouse relative movement setting:

<img width="836" alt="Screenshot 2024-02-22 at 7 42 50 AM" src="https://github.com/mihaip/infinite-mac/assets/13210399/39aeaedb-48c5-4e48-b450-18c6a05c3a2f">

**Comment by mihaip** [comment]
I have an early version of this if you want to try it -- on a touch device to go https://infinitemac.org/1994/System%207.5 and tap the "Trackpad" option at the bottom of the screen. When it's enabled, the entire screen becomes a virtual trackpad. It supports basic tap-to-click gesture, as well as a a tap-then-drag to do a drag while the virtual mouse button is down. It works well for double-clicking and dragging windows around, but opening of pull-down menus is pretty finicky.

**Comment by robinhood2014** [comment]
Good progress. As you said, pull-down menu opening needs work, and I did notice it was a little bit on the slow side at times. Other than that, the emulated trackpad works quite well.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by that-ben** [comment]
HA! That's pretty neat! Thanks for implementing the trackpad functionality!
