### ISSUE TITLE
Could the mouse acceleration setting not be persistent?

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#295]
Could the mouse acceleration for Apeiron not be persistent? It could confuse users if they enabled it for Apeiron at some point and then a few days or weeks pass and they attempt to use IM again but forgot that they left that setting turned on.  It makes it very hard to use the Finder.

**Comment by mihaip** [comment]
All of the emulator settings are persisted together ([code](https://github.com/mihaip/infinite-mac/blob/b4d266bf964d6e1aeaa2f81a0399379df13f437d/src/Mac.tsx#L106-L110)) and I don't think it's worth the complexity to break out the relative movement one.

**Comment by that-ben** [comment]
If we had status "LED" showing at the bottom of the emulator in the bezel or something, it would help realize we're on mouse acceleration or not.
