### ISSUE TITLE
HTTP Status 500 on every CD Image

### ISSUE THREAD

**Issue by fullpwn** [mihaip/infinite-mac#297]
<img width="1212" alt="image" src="https://github.com/mihaip/infinite-mac/assets/57821130/cf87c4bb-9854-436f-b2af-25085331b450">

**Comment by parkerlreed** [comment]
500 is remote server error. Appears to be working here. Check to see if you can reach the sources outside of the emulator.

**Comment by mihaip** [comment]
@parkerlreed is correct that this is an error relating to the (archive.org) server that the CD-ROM image is being streamed from. I'll look into making the message friendlier so that it's easier to understand what is happening.

**Comment by kiljorn1109** [comment]
@mihaip isn't this because of the image file chunks not being generated? nearly all the links work for download

**Comment by that-ben** [comment]
I've been getting this 90% of the time since last year.  I also sometimes get the page where ARCHIVE.ORG claims it's overloaded and that I need to try again in a couple seconds, so I'm pretty sure they do this to prevent the server from crashing due to high load or too many requests in a short period of time.

**Comment by spudpiggy** [comment]
> I've been getting this 90% of the time since last year whenever I try to stream disk images on IM from ARCHIVE.ORG. Accessing them as a download in my browser always works, except for a few times where I also get the page where ARCHIVE.ORG claims it's overloaded and that I need to try again in a couple seconds, so I'm pretty sure they do this to prevent the server from crashing due to high load or too many requests in a short period of time.

I recommend downloading the ISO manually and then mounting the downloaded copy instead of streaming from archive.org.
Their download servers are almost always terrible (several hundred kb/s) so larger isos will error if they don't download fast enough. Try finding the iso on macintoshgarden or another service with actually good file servers.

**Comment by that-ben** [comment]
The thing is that I also tried to directly stream an ISO from MR and it does the same thing.  I suspect there's some kind of bug in the file streamer or that it asks too many chunks at the exact same time which makes website firewalls suspicious or something alike.  I can guarantee you that when I test with MR, the website is NOT overcrowded, I can see the Apache status, open slots, bandwidth, etc... and it should stream at multiple megabytes a second, so this is not the issue.

**Comment by mihaip** [comment]
What I think is happening is that the Cloudflare Worker is (at least sometimes) fetching the entire disk image, even though I'm only requesting a small piece of it. Using the image that @that-ben provided, the first 4 chunks are from relatively early in the file, but the one that fails is ~200MB into it.

![Screenshot 2024-03-21 at 23 28 21@2x](https://github.com/mihaip/infinite-mac/assets/513813/a5ff722f-068c-488f-9759-5838222deca2)

I think the reason why it eventually succeeds (if you reload enough times) is that the whole file ends up being cached by Cloudflare, and then it can respond to these range requests from its cache.

I'll look into workarounds.

**Comment by mihaip** [comment]
Based on https://community.cloudflare.com/t/cloudflare-worker-fetch-ignores-byte-request-range-on-initial-request/395047 and https://community.cloudflare.com/t/how-do-you-do-the-equivalent-of-the-page-rule-cache-level-bypass-in-a-worker-fetch/388255/5 I enabled bypassing the Cloudflare cache to archive.org and a few other sites and it seems to be working better now.

**Comment by that-ben** [comment]
@mihaip Would you like me and you to test things out in real time on the MR server sometime? Perhaps together we can find why Cloudflare sometimes requests the whole file and fix the issue or find a workaround that would also work on other web servers?

**Comment by mihaip** [comment]
> How is CloudFlare even relevant for the task of streaming chunks from various places on the internet?

Cloudflare is where the site is hosted (using their [Workers](https://developers.cloudflare.com/workers/) product), there is no other server component for Infinite Mac. CD-ROM chunks have to be proxied through the Cloudflare worker because they can't be fetched from the browser directly (archive.org and others don't send CORS headers to allow cross-origin fetching).

**Comment by that-ben** [comment]
Oh I see.  Wait, so does that mean that my local implementation (or others') of IM will stop working the day you unplug CloudFlare?

**Comment by mihaip** [comment]
If you're not requesting anything from infinitemac.org (which you don't appear to be) then you're not dependent on what's running on Cloudflare.

**Comment by that-ben** [comment]
Ah, I see what you mean, thanks for the clarification.

**Comment by kiljorn1109** [comment]
Sorry for the offtopic, by any chance can you tell me, how does the LAN exactly work? Couldn't get it to work neither on a cloudflare worker or on your site, the zones can have any name? Or are they set to something?

**Comment by fullpwn** [comment]
That is definitely off topic and not really suited for this issue. 

I recommend you probably either contact the developer directly or create a separate issue.

**Comment by mihaip** [comment]
Closing this out, CD-ROM images seem to be more reliable now.
