### ISSUE TITLE
Worker stuff

### ISSUE THREAD

**Issue by kiljorn1109** [mihaip/infinite-mac#299]
How did you manage to get npm run sync-disks? Rclone doesen t seem to want to authorize cloudflare for me

**Comment by mihaip** [comment]
Where are you syncing to? Did you end making an rclone.conf file based on https://github.com/mihaip/infinite-mac/blob/main/scripts/rclone.conf.example?

**Comment by kiljorn1109** [comment]
> Where are you syncing to? Did you end making an rclone.conf file based on https://github.com/mihaip/infinite-mac/blob/main/scripts/rclone.conf.example?

Yeah, tried yours made mine... nome of them work i get unauthorized when running npm run sync-disks

**Comment by mihaip** [comment]
You may need to make sure that the API token has read/write permissions to the bucket:
![CleanShot 2024-03-09 at 16 15 08@2x](https://github.com/mihaip/infinite-mac/assets/513813/8e4fe57d-24ec-4324-b811-f018a7f05310)

More generally, what are you trying to do? The R2 bucket is only necessary if serving large disk images, I was using Workers KV until very recently (see numbers in #288 and the commit that's associated with it).

**Comment by kiljorn1109** [comment]
Wanna serve big images around 500 gb worth, the r2 has permissions that baffles me... it has admin and the object r/w. After research i found out to possibly from rclone.. gonna try tommorow again

**Comment by kiljorn1109** [comment]
Gonna post a screenshot of the output with -vv as the guides on the web talked about, maybe u went thru that too lol

**Comment by kiljorn1109** [comment]
Success... something with the VM i was using... gotta get the LAN functional now lol
