### ISSUE TITLE
Support for international Mac OS versions?

### ISSUE THREAD

**Issue by gingerbeardman** [mihaip/infinite-mac#30]
Most of my vintage Macintosh work is done in Japanese System 7 (specifically J-7.5.3) which uses MacJapanese encoding (rather than MacRoman). 

There are dozens of other international versions of System 7 and 8, with lots of text encoding systems. Luckily the installers are all available on WinWorld etc and the official Apple text encoding mappings are preserved as part of Tcl. 

I'd be interested to hear what might be involved to support arbitrary International Macintosh versions?

ps: insanely great work on this!

**Comment by mihaip** [comment]
This should most likely work using a different base image, though I'm not sure how it will handle the ExtFS file system, which generally assumes MacRoman encoding. Will play around. Do you have a preferred base disk or install image?

**Comment by gingerbeardman** [comment]
J-7.5.3 is my preferred system: https://winworldpc.com/product/mac-os-7/75

Fingers crossed that ExtFS "just works"!

Thanks for looking into this.

**Comment by mihaip** [comment]
https://kanjitalk7.app should be up and running. Combined with the fix from #26 this allows disk images like the one from https://macintoshgarden.org/games/hanafuda-stack to be dragged, mounted and played:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/513813/163726017-61c63044-1519-4b55-be3b-478312646415.png">

**Comment by gingerbeardman** [comment]
Many thanks!
