### ISSUE TITLE
System 5.0 and 5.1 freeze the MacvMac-II.js shortly after boot sequence starts

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#300]
As seen on here: https://infinitemac.org/1987/System%205.0?infinite_hd=false&saved_hd=false&machine=Mac+II

**Comment by mihaip** [comment]
Duplicate of #165 -- I believe this is a limitation of Mini vMac itself.

**Comment by that-ben** [comment]
Whoops, I missed that thread.  Thanks.
