### ISSUE TITLE
MacEmu

### ISSUE THREAD

**Issue by NGGYUPython** [mihaip/infinite-mac#301]
macemu
autor is not me

**Comment by mihaip** [comment]
@NGGYUPython I don't understand, what do you mean?

**Comment by LagLifeYT** [comment]
They are probably referring to [this](https://github.com/kanjitalk755/macemu/) (which is already used in Infinite Mac)

**Comment by mihaip** [comment]
@LagLifeYT I guess that makes sense, and yes, I use Basilisk II and SheepShaver from that repo.
