### ISSUE TITLE
Zone LAN

### ISSUE THREAD

**Issue by kiljorn1109** [mihaip/infinite-mac#303]
Hello, how does the worker exactly do the lan connection between multiple machines? What does it actually do? I didn t manage to get it to do more than show the connected peers in the bottom corner of the monitor frame. Any idea what that could be coming from? Thanks mihai.

**Comment by bshep** [comment]
as far as i understand it uses a cloud flare worker to proxy the data between instances.

there is ONLY lan connectivity, NO internet access from the emulated macs.

**Comment by kiljorn1109** [comment]
I have the cloudflare worker edited and configured for my domain, i understood that no internet conectivity is available i m looking exactly for LAN

**Comment by bshep** [comment]
> I have the cloudflare worker edited and configured for my domain, i understood that no internet conectivity is available i m looking exactly for LAN

Then it should work just as if they were connected using appletalk, you can turn on file sharing etc.

**Comment by kiljorn1109** [comment]
Welp it just doesen't apple talk does not show on macos 8.1

**Comment by bshep** [comment]
> Welp it just doesen't apple talk does not show on macos 8.1 or the others that have the appletalk option

On 8.1, 

In emulated mac #1: open the 'file sharing' control panel, fill in the 3 fields at the top, click start file sharing ( wait about 2-3 minutes while it starts up ).

In emulated mac #2: open chooser, click on 'apple share' , your mac #1 should show up.

If you want to share a folder then select it on the finder then do file->sharing and edit the settings

**Comment by mihaip** [comment]
https://www.youtube.com/watch?v=cPu7o6F_lwk also has a demo (of both Marathon networking and file sharing).
