### ISSUE TITLE
Rename Outside World's surrounding folder in generated ZIP file please?

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#307]
I have a request: Would it be possible for IM not to name the folder in the uploaded ZIP file in Outside World the exact same name as the file? Perhaps prepend "_" to the folder name would be nice or something like that? It makes it frustrating to extract the contents, because you cannot move the file out of the surrounding folder that IM is creating without renaming one of them manually first.

**Comment by mihaip** [comment]
I kind of like the name being clean. I use it to create archives for the Infinite HD library (see .zips in https://github.com/mihaip/infinite-mac/tree/main/Library/Control%20Panels%20%26%20Extensions and other directories). No one else has mentioned this as being a problem.

If you'd like to change it in the version of Infinite Mac that you host, you can tweak the naming logic at https://github.com/mihaip/infinite-mac/blob/77f043a19bdf20e6f071ad798806d36290f9a850/src/emulator/emulator-ui-extractor.ts#L206
