### ISSUE TITLE
Marathon Trilogy Bug

### ISSUE THREAD

**Issue by MarathonMasaster** [mihaip/infinite-mac#308]
Im unable to use the "Command-Option" while pressing new game to select a level instead of start at the beginning of the game, I don't know if this is the system Im using to run InfiniteMac, or if it's InfiniteMac that bugging. May you please test it to see if it works on your end?

**Comment by that-ben** [comment]
Which modern OS are you using? Windows or macOS? I'm asking because if you're under macOS, have you tried to hold down Control-Option instead of Command-Option?

**Comment by MarathonMasaster** [comment]
Perhaps I'll try Control-Option then and see if that changes anything

**Comment by MarathonMasaster** [comment]
After testing with Control and Command, the issue doesn't seem to be those, but the Option key. I can press New Game while holding Command, but not while also holding down Option (Alt on my Computer, and Command being Control).

**Comment by mihaip** [comment]
This works for me (using Chrome on a Mac, either with the literal combination, or with Control-Option if using the "Swap Control and Command" Infinite Mac setting)

![Screenshot 2024-04-12 at 20 41 29@2x](https://github.com/mihaip/infinite-mac/assets/513813/02de53c6-e86d-4d47-bc37-756110b22a3b)

You can use the Key Caps DA (from the Apple menu) to check how various keys are being reported.

More details (which browser and OS are you running, which version of Mac OS are you emulating) are needed to investigate this further.
