### ISSUE TITLE
Missing Outside World

### ISSUE THREAD

**Issue by jjsmeets** [mihaip/infinite-mac#309]
When using System 7.5.3 and using configure button (next to Run) and the changing the machine to MacII (not MacIIfx) and then pressing done, a configured mac appears. Two strange things:
1 The System disk icon is a floppy and not a harddisk icon
2 And much more important: NO Outside World Drive is loaded.

Do not now if it is important but here is my host environment
Windows11
Chrome (Chrome is up-to-date: Versie 123.0.6312.123 (Officiële build) (64-bits)

**Comment by that-ben** [comment]
The "normal" System 7.5.3 configuration is emulated via Basilisk II while Mac II emulation is done via the Mini vMac emulator and that's why the drives appear as a floppy with the letter "V" on them.  Mini vMac does that.

As for your question 2, could you further explain how you mounted it via Basilisk II? Was that a disk image that you dragged and dropped onto the emulator or a link that you copy/pasted in the "Customize" screen before launching the emulator or something else? Can you link to the disk image in question?

**Comment by jjsmeets** [comment]
Hello I have added 3 screenprints showing what happens.I always use system 7.5.3picture 01 show the customization dialog after pressing customizepicture 02 show the result  where no outside world is presentpicture 03 show what happens when not using any customization but directly pressing the run button.
This all also happens on system 7.5 and system 7.0 (which I have also used). The Saved HD was created by infinitemac when I first used the emulator. Later I have used drag and drop to add sit-files to the emulator and unsitting these files. These files always show in the Outside Wold Download folder. I Also used the Upload folder by drag/dropping folders on the outside world and when copy operation is ready move the to Uploads
Note: when dragging a file to the emulator where outside wolrd is missing, the drop of the file does NOT magically let the Outside World Drive Appear.
Greetings John Smeets  

    Op dinsdag 16 april 2024 om 15:03:43 CEST schreef Ben ***@***.***>:  
 
 


The "normal" System 7.5.3 configuration is emulated via Basilisk II while Mac II emulation is done via the Mini vMac emulator and that's why the drives appear as a floppy with the letter "V" on them. Mini vMac does that.

As for your question 2, could you further explain how you mounted it via Basilisk II? Was that a disk image that you dragged and dropped onto the emulator or a link that you copy/pasted in the "Customize" screen before launching the emulator or something else? Can you link to the disk image in question?

**Comment by mihaip** [comment]
This is expected -- the Mac II is emulated by a different emulator (Mini vMac) which does not support the "The Outside World" shared drive. This why the default for 7.5.3 (and most other System 7 versions) is the Quadra 650, which is emulated by Basilisk II, which does have "The Outside World".
