### ISSUE TITLE
Not an Issue, Just Praise

### ISSUE THREAD

**Issue by marciot** [mihaip/infinite-mac#31]
Hello @mihaip, I am very impressed at what you accomplished here, in particular with the upload and download feature! That is amazing! That feature was something I always wanted for my own emulator web site (http://retroweb.maclab.org) so I commend you on figuring out how to do it! I might have to dig into your source code to figure out how you pulled this off!

**Comment by mihaip** [comment]
Thanks! My [blog post](https://blog.persistent.info/2022/03/blog-post.html) has some pointers, including links to commits if you're curious.

**Comment by marciot** [comment]
@mihaip: Oh, thank you. That write-up is fantastic!
