### ISSUE TITLE
Rhapsody/Mac OS X Server 1.0

### ISSUE THREAD

**Issue by mattl** [mihaip/infinite-mac#310]
It would be good to see Mac OS X Server 1.0 (or 1.1, 1.23, etc) running on an emulated Power Mac G3 B&W.

I recently got it working on real hardware and someone on the UK-NEXTSTEP-USERS list suggested I suggest it here.

https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2404&L=UK-NEXTSTEP-USERS&O=D&P=9404

**Comment by that-ben** [comment]
Probably that it will work in InfiniteMac under the DingusPPC emulator soon-ish.

**Comment by mihaip** [comment]
Yes, this will need a different emulator - QEMU (#72) or DingusPPC (#219). I wouldn't be optimistic about it happening soon thuogh.
