### ISSUE TITLE
Adding more drivers breaks drive image on real macs

### ISSUE THREAD

**Issue by erichelgeson** [mihaip/infinite-mac#312]
Just noticed this but now when exporting a Saved HD with these additional drivers https://github.com/mihaip/infinite-mac/commit/2f70a5416079603c2cc0acd36950608fb86ad597 the resulting drive is no longer able to be used in older real macs via BlueSCSI such as the Mac Plus.

It may be worth having a drop down or similar for where it is going - eg Dingus vs BlueSCSI (or maybe ide/scsi? not sure on the UX). We've found that the Apple HD SC 7.3.5 driver is the most compatible with real hardware - working from the Plus up to a Beige G3. 

Thanks again for your awesome work!

**Comment by DB4000K** [comment]
Not sure if the issue is just for mac plus or any other classic macs. I could test others. And I like @erichelgeson dropdown idea.

**Comment by mihaip** [comment]
I only needed the extra drivers for DingusPPC when emulating the Beige G3 (it uses the IDE bus), so it was easier to partially undo my change, and keep the Apple SCSI 4.3 driver for the .hda export.
