### ISSUE TITLE
getting osx in infinite mac

### ISSUE THREAD

**Issue by Pierrestro** [mihaip/infinite-mac#318]
i'm uploading it soon (when internet let me to) 
![image](https://github.com/mihaip/infinite-mac/assets/91497360/9dd5a7ea-4c54-40a9-8ae3-1e659d43c4a4)

- [x] uploaded

**Comment by mihaip** [comment]
Is this just the installer? That has worked for a while: https://github.com/mihaip/infinite-mac/issues/219#issuecomment-1770123646

**Comment by Pierrestro** [comment]
> Is this just the installer? That has worked for a while: [#219 (comment)](https://github.com/mihaip/infinite-mac/issues/219#issuecomment-1770123646)

no it's installed but my internet sucks and keep disconnecting me every 5 minutes I will get a new rooter soon so I will be able to upload

**Comment by Pierrestro** [comment]
My laptop has died I'm trying to recover my data and upload the image to archive.org

**Comment by that-ben** [comment]
![f054c6b9cec94fb3d31069d3e83e806b](https://github.com/user-attachments/assets/148db726-4701-464e-9b2d-dcb610b38ff2)

**Comment by Pierrestro** [comment]
i cant test it i have 2 of them its just too slow https://archive.org/details/macosx_6gb

**Comment by mihaip** [comment]
I got this working with a 10.2 install made in QEMU, see https://github.com/mihaip/infinite-mac/issues/219#issuecomment-2244328841

**Comment by Pierrestro** [comment]
> I got this working with a 10.2 install made in QEMU, see [#219 (comment)](https://github.com/mihaip/infinite-mac/issues/219#issuecomment-2244328841)

Thx but do we need to investigate qemu I said that because I still haven't repaired my laptop yet

**Comment by bshep** [comment]
> > I got this working with a 10.2 install made in QEMU, see [#219 (comment)](https://github.com/mihaip/infinite-mac/issues/219#issuecomment-2244328841)
> 
> Thx but do we need to investigate qemu I said that because I still haven't repaired my laptop yet

Can you explain what your laptop has to do with this project?

**Comment by JosiahAppsInc** [comment]
Well, guys, I found out how to get OS X to boot. First of all, turn on the "Swap control and command keys" option. 
Next, As the OS boots, hold the Control + C Keys. You can see it typing cccccc in the terminal.
Next, when it asks for the login, enter in the WORNG password. 
And now, wait about 2 minutes. Then, the OS will find out there is no accounts registered, and you will be automatically booted into the OS.

If the OS says restart the computer, just reload the webpage and try again. Same if the Kernel Panics.
<img width="804" alt="Screenshot 2024-12-30 at 9 00 22 AM" src="https://github.com/user-attachments/assets/edbd07ab-ed53-4685-a2db-a7f186436487" />

**Comment by JosiahAppsInc** [comment]
Image above shows that this works. Try to boot the OS ONLY on this link. **Any other config will fail.**

https://infinitemac.org/run?disk=Mac+OS+X+10.2&infinite_hd=true&ram=128M

**Comment by JosiahAppsInc** [comment]
Well, It works! Enjoy!

Also, pls follow my GitHub. I work hard to make this stuff.

**Comment by MesaBlack** [comment]
It did a kernel panic
