### ISSUE TITLE
King's Quest V freezes at the title screen?

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#320]
King's Quest V hangs on the title screen after the Sierra logo animation (the emulator is not frozen though, you can click on the desktop and continue to use Mac OS).  This also happens under native Basilisk II 2.5.  Is there a way to fix the emulator so that it runs?

I own this game since the early 90's and this worked perfectly fine on our LC 475 under System 7.1 and 7.5.  I have tried a number of different BasiliskII.js configurations with different System versions, extensions off, the supplied MIDI driver, etc... every single config I have tried yields the same result: it hangs at the title screen.  The funny thing is if you click on the desktop and then pull SPECIAL > SHUT DOWN, then KQ5 asks you if you really want to quit and the interface buttons actually work.  So it's not really hung, it just waits for some event that never fires or something like that.

You can grab the pre-installed disk image here: https://www.macintoshrepository.org/files/direct/6171_Kings-Quest-V.dsk

<img width="1323" alt="Screenshot 2024-05-22 at 11 12 06 AM" src="https://github.com/mihaip/infinite-mac/assets/13210399/c9bdeb08-a510-4c2d-83a3-9cfc8de8708e">

**Comment by dingusdev** [comment]
[This is a well-documented issue with Sierra games from the early 90's.](https://www.benshoof.org/blog/sierras-macintosh-timebomb )

**Comment by that-ben** [comment]
Oh, how interesting, so it's related to Y2K?

**Comment by that-ben** [comment]
Well, I'll be damned.
