### ISSUE TITLE
getting osx there!!!

### ISSUE THREAD

**Issue by Pierrestro** [mihaip/infinite-mac#321]
- [x] getting osx 10.2 installer to work
- [ ] trying to fix drive not detected
- [ ] getting osx 10.2
- [ ] getting osx 10.2.8
- [ ] patching osx 10.3
- [ ] trying to get 10.3
- [ ] mihaip has putted osx into infinite mac

**Comment by Pierrestro** [comment]
l

**Comment by mihaip** [comment]
Please don't file issues that are duplicative or non-technical in nature. Mac OS X requires a different set of emulators, #62 and #219 are tracking that work. Please only comment if you have something technical to contribute to those conversations.
