### ISSUE TITLE
Issues with loading CD-ROMS with various OSes

### ISSUE THREAD

**Issue by ewe2** [mihaip/infinite-mac#327]
This might be related to #166 as you see fit. Running 6.0..8 and loading the Legacy Recovery CD often gets the question that the disk needs minor repairs, then the emulator reports it cannot load a chunk from the media.

Sometimes this fix is needed ones, sometimes multiple times, you get a corrupted disk anyway. There might be session-related information here, I have subsequently loaded a later OS 7.1 and the disk is loaded without an issue. However when trying to use the disk for making an install disk, I run into the same kind of error with the emulator saying it cannot load a chunk from the media.

![image](https://github.com/user-attachments/assets/86ea2aea-0b06-4b0b-9ef0-aa038162b50d)

If there is any other debugging/troubleshooting I can do from my end, let me know.

**Comment by mihaip** [comment]
Most of the CD-ROM images are served from archive.org, and I have not been able to get them to consistently load. Unclear if it's a reliability issue with archive.org, or if it's something that I'm doing wrong.

**Comment by ewe2** [comment]
Ah thanks is there a way i can load them into the interface manually or do I have to resort to the emulators?

**Comment by mihaip** [comment]
You can download the .iso from archive.org and then drag it into the window to mount it. That way it'll read from the local file and it'll be faster and more reliable.
