### ISSUE TITLE
Mac OS X 10.4 +

### ISSUE THREAD

**Issue by YD711YT** [mihaip/infinite-mac#328]
According to my understanding, DingusPPC can only emulate up to Mac OS X 10.3(Panther). So how can 10.4 and 10.5 (still supports PowerPC) and 10.6+ (Intel x86) be emulated on infinite Mac in the future?

**Comment by MaddTheSane** [comment]
There is a [fork](https://github.com/Wack0/dingusppc-nt) of DingusPPC that targets New World Macs (specifically to work on porting Windows NT 4.0 to Power Macs). Most likely adding support for the first-gen New World Macs would be fairly easy as there's no hardware actually removed (as far as the chipset is concerned. A lot of the first-gen New World Macs still had places to add a header for floppy drives, and even the tray-loading drive has a place you can add an ADB port). Second-gen might need more work as hardware was removed, no doubt to cut down on cost.

Also, there is XPostFacto that can make older Macs (including upgraded pre-G3 Power Macs) run 10.3 (Apple only supported up to 10.2 on the Beige G3) or 10.4 (10.5 added the requirement of having a G4 or G5 or Intel).

**Comment by mihaip** [comment]
DingusPPC already has a [Yosemite](https://github.com/dingusdev/dingusppc/blob/master/machines/machineyosemite.cpp) (Blue & White G3) machine definition. The fork at https://github.com/joevt/dingusppc has more full-featured implementation of it. Will track this as part of the general DingusPPC work in #219.
