### ISSUE TITLE
Fix trackpad input on iPad

### ISSUE THREAD

**Issue by mihaip** [mihaip/infinite-mac#33]
Report that it didn't: https://twitter.com/kaplanfx/status/1509993270096498693

**Comment by stedog** [comment]
I can confirm as well that the trackpad for the Magic Keyboard on iPad Pro is not working.  Touch does work, however.  Love this, BTW!

**Comment by VirtualWolf** [comment]
Yep, can confirm as well. I'm on a 2018 11" iPad Pro with the Magic Keyboard, if it matters.

**Comment by parkerlreed** [comment]
Same thing happens on Android. Using a Samsung tablet with their keyboard cover, the mouse works normally but when hovering over infinite Mac, disappears and doesn't control the emulated cursor.
