### ISSUE TITLE
Feature Suggestion: Add Emulation for IIci SE/30

### ISSUE THREAD

**Issue by OctocatBoi** [mihaip/infinite-mac#331]
This is a suggestion for infinite mac, i was wondering if you could allow emulation of the se/30 and iici in the next update, For The IIci, you could use the mame emulator and for the se/30 use mini vmac. Now i think be experimental if its added so i will wait.

**Comment by mihaip** [comment]
#158 was filed to investigate MAME, but it's not on my roadmap.

I'm not seeing the SE/30 as a supported machine for Mini vMac (https://www.gryphel.com/c/minivmac/var_serv.html lists all known machines, and it only has the SE). Generally Mini vMac only supports 68000 and 68020-based machines.

**Comment by OctocatBoi** [comment]
thats ok, i think its kinda understandable, since that would be time consuming, mainly mame, so yea, fair enough, thats ok.

**Comment by mihaip** [comment]
Feel free to subscribe to #158 - if I do work on MAME updates will happen there.
