### ISSUE TITLE
the website stopped working

### ISSUE THREAD

**Issue by minefox199** [mihaip/infinite-mac#334]
when I was trying to boot macOS 8.5 it got stuck on the loading data files and keep on flashing 
![image](https://github.com/user-attachments/assets/c55de0c8-f812-492d-a580-9dc31d64f6f6)

**Comment by mihaip** [comment]
Works for me. Can you add a few more details:
- Which browser you're using.
- The URL that you're loading (especially if you're using a custom instance)
- Any errors in the browser developer tools console

**Comment by minefox199** [comment]
found the problem 
![image](https://github.com/user-attachments/assets/4b9a3668-0866-4761-a25f-37dc61dbdd93)

**Comment by minefox199** [comment]
and more errors 
![image](https://github.com/user-attachments/assets/2d39f512-a737-46c6-93d6-26073aff7d54)

**Comment by mihaip** [comment]
Those all look like errors from extensions.

**Comment by minefox199** [comment]
also I'm using microsoft edge and I'm using the macOS 8.5 install disk

**Comment by minefox199** [comment]
even when trying to boot from my iso file from my pc to the emulator it wont work

**Comment by that-ben** [comment]
Disable AdBlock and/or new extensions you've enabled today and you will find one that causes this.  InfiniteMac's SheepShaver.js works for me.

**Comment by minefox199** [comment]
![Screenshot 2024-08-24 184114](https://github.com/user-attachments/assets/10ac5e47-8787-4b3e-9a02-5469f2e68d7b)
I got these working at least
![Screenshot 2024-08-24 183145](https://github.com/user-attachments/assets/e73b0e73-d325-4900-a665-0c69b88ba84f)
