### ISSUE TITLE
Some additions to the Ambrosia collection

### ISSUE THREAD

**Issue by Iritscen** [mihaip/infinite-mac#335]
Just a request – the "Games:Ambrosia Software" folder is a solid start, but I wonder if a few more of the classics could be added:

Ares
EV Nova
EV Override
Harry the Handsome Executive

This is far from an exhaustive list, but people are of course free to bring in more of the Ambrosia games from MacGarden/Repo if they so choose.  I just think people will have a special interest in these four.

(On a side note, was it intentional that both Apeiron 1.0.2 and 1.0.3 were placed in this folder?)

**Comment by dingusdev** [comment]
I think the main reason those weren't added yet was because those games use a different registration system and also are limited when they aren't registered. With the registration key algorithm being cracked and a key maker program being released by Andrew Welch himself, maybe those could be added.

**Comment by alexjyong** [comment]
Mars Rising would be cool to add as well.

**Comment by Darksaber3** [comment]
Just a note you can download those all on Macintosh garden now. Put them into your saved folder and pull out your old license code every time you boot. Also make sure not to hit caps lock or it will be caps locked permanently until you reboot your machine.

**Comment by BiggerJ** [comment]
Also, Ambrosia Software's former president and Chief Thaumaturge, Andrew Welch, released a serial number generator for Ambrosia's games named Decoder Ring - it's on Macintosh Garden. While it's for OSX, there's also a corresponding Buck's Serial Number Generator plugin on the same Macintosh Garden page - BSNG works in OS9, and thus Infinite Mac.

**Comment by mihaip** [comment]
I added my favorites. With the Macintosh Garden integration it's pretty easy to install more onto Saved HD, so I'm not planning on adding more.
