### ISSUE TITLE
Emulator error  

### ISSUE THREAD

**Issue by youvebeenjohned** [mihaip/infinite-mac#338]
How to fix error (____
.___s) ppcmmu.cpp559 FATL| ABORT: Instruction fetch from unmapped memory at 0xF800000!
![Uploading image.jpg…]()

**Comment by mihaip** [comment]
Looks like your screenshot didn't finish uploading. Which emulator/OS were you trying this with?

**Comment by youvebeenjohned** [comment]
macOS 9.22

**Comment by mihaip** [comment]
That's a DingusPPC-based emulation, and it's known to be relatively unstable. There's no need to file separate bugs about DingusPPC, you can follow progress by subscribing to #219.
