### ISSUE TITLE
Mac OS 9.0.4 suffers a buffer allocation error on Mac G3 Beige (DingusPPC).

### ISSUE THREAD

**Issue by MesaBlack** [mihaip/infinite-mac#339]
![image](https://github.com/user-attachments/assets/a13d6b49-f917-4caa-8cd5-21f02eb1ad3e)

[here's how](https://infinitemac.org/2000/Mac%20OS%209.0.4?machine=Power+Macintosh+G3+%28Beige%29)

Edit: Oh, maybe it's sheepshaver things...

**Comment by that-ben** [comment]
If you are going to emulate Mac OS 9.0.4 then it would be best to do it under SheepShaver at the moment.  DingusPPC is not developed enough for Mac OS 9.0.4.  It also will not boot 9.0 and 8.6 which will freeze with current DingusPPC implementation.  On the other hand, Mac OS 8.1 will boot fine and Mac OS 8.5 will seemingly boot but shortly after displaying the desktop, it will freeze.  For 9.0.4 down to 7.5.3, the best PowerPC emulator at the moment remains SheepShaver.

**Comment by MesaBlack** [comment]
aight

**Comment by mihaip** [comment]
Yes, DingusPPC is relatively unstable, there's no need to file separate bugs about it. You can follow progress by subscribing to #219.
