### ISSUE TITLE
Drag-in support for bin/cue files.

### ISSUE THREAD

**Issue by BiggerJ** [mihaip/infinite-mac#341]
You noted earlier that you only added URL support for bin/cue CD ROM images. Given that many CD images online are inside compressed files and that the Internet Archive's slow download speeds seem to often result in error messages, could you please add drag-in support for bin/cue images?

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
I put the necessary dlls in the archive

**Comment by that-ben** [comment]
+1 I would really like that too.

**Comment by mihaip** [comment]
This should work now. You can drag in just the .bin file. If it's bigger than 100 MB I assume it's a CD-ROM image with the MODE1/2352 encoding.

**Comment by that-ben** [comment]
What a great feature! Thanks.
