### ISSUE TITLE
Make it harder to accidentally close the browser tab when Command-W is pressed

### ISSUE THREAD

**Issue by davidfstr** [mihaip/infinite-mac#343]
Issue #36 highlights that pressing Command-W will close the emulated tab. I might suggest forcing a confirmation prompt to appear instead, so that there's less chance that the emulated state is lost.

I was able to force a confirmation prompt to appear by registering a ["beforeunload" event](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event). See steps below for details.

Steps:
* Run a machine: https://infinitemac.org/1994/System%207.5
* Open at least one Finder window.
* Open the JavaScript console and paste the following code, derived from [this MDN page](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event):
    * `window.addEventListener("beforeunload", (event) => { event.preventDefault(); event.returnValue = true; });`
* Press Command-W

Expected + Actual Results:
* Browser shows the following popup:
<img width="372" alt="Screen Shot 2024-09-29 at 7 48 19 PM" src="https://github.com/user-attachments/assets/5c569d97-5574-496e-9bbc-ed7fdfbf7bd1">

**Comment by that-ben** [comment]
+1 Accidentally CMD-W in IM happens to me all the time.

**Comment by mihaip** [comment]
@davidfstr this is a great suggestion, it should be live now.

**Comment by davidfstr** [comment]
@mihaip You rockstar! It works great~ 🙏
