### ISSUE TITLE
I can't resize window of sheepshaver emulator with installed OS 9

### ISSUE THREAD

**Issue by Farooq87** [mihaip/infinite-mac#344]
I can't resize window of sheepshaver emulator with installed OS 9. It automatically shrinks to 640x480 small window on my desktop no matter what resolution for window I set in configuration.

![image](https://github.com/user-attachments/assets/c1332b8c-3a67-40db-b5ef-4ab9ae6403f7)
![image](https://github.com/user-attachments/assets/a2dfe261-59d5-403b-a0c1-c1fa42a206e2)

**Comment by Farooq87** [comment]
Sheepshaver preferences 

disk macos904.hfv
cdrom G:\
extfs 
screen dxwin/1100/830/32
seriala COM1
serialb COM2
ether slirp
rom newworld86.rom
bootdrive 0
bootdriver 0
ramsize 536870912
frameskip 0
modelid 14
cpu 68040
fpu true
nocdrom false
nosound false
nogui false
noclipconvert false
nofloppyboot false
noscsi true
ntdx5hack false
rightmouse 1
keyboardfile BasiliskII_keyboard
pollmedia false
priority_ether_run 0
priority_ether_idle 0
priority_serial_in_run 0
priority_serial_in_idle 0
priority_serial_out_run 0
priority_serial_out_idle 0
priority_cpu_run 0
priority_cpu_idle -1
priority_60hz_run 1
priority_60hz_idle 1
priority_1hz_run 1
priority_1hz_idle 1
priority_pram_run 0
priority_pram_idle -1
priority_gui_run 1
priority_gui_idle 0
priority_gdi_run 0
priority_gdi_idle -1
priority_dx_run 0
priority_dx_idle -1
priority_fb_run 0
priority_fb_idle -1
priority_sound_run 0
priority_sound_idle 0
noaudio true
debugscsi 0
debugfilesys 0
debugserial 0
framesleepticks 12
showfps false
stickymenu true
etherpermanentaddress true
ethermulticastmode 0
disable98optimizations false
realmodecd false
soundbuffers 3
soundbuffersize8000 1024
soundbuffersize11025 2048
soundbuffersize22050 2048
soundbuffersize44100 4096
nosoundwheninactive true
mousewheelmode 1
mousewheellines 3
mousewheelreversex false
mousewheelreversey false
mousewheelclickmode 1
mousewheelcust00 +37+3B-3B-37
mousewheelcust01 +37+3C-3C-37
mousewheelcust10 
mousewheelcust11 
usealtescape true
usealttab true
usecontrolescape true
usealtspace true
usealtenter true
disableaccuratetimer false
guiautorestart 0
gethardwarevolume true
enableextfs true
usentfsafp false
extdrives #CDEFG
typemapfile C:\SheepShaver_MacOS904_839mb\Sheep\BasiliskII.ftm
debugextfs 0
portfile0 C:\B2TEMP0.OUT
portfile1 C:\B2TEMP1.OUT
DX_fullscreen_refreshrate Monitor default
mousemovementmode 0
usestartupsound true
smp_ethernet 0
smp_serialin 0
smp_serialout 0
smp_cpu 0
smp_60hz 0
smp_1hz 0
smp_pram 0
smp_gui 0
smp_gdi 0
smp_dx 0
smp_fb 0
smp_audio 0
idlesleep 1
idlesleepenabled false
idletimeout 0
routerenabled false
ftp_port_list 21
disablescreensaver false
keyboardtype 5

**Comment by that-ben** [comment]
This is completely unrelated to the InfiniteMac project.

**Comment by Farooq87** [comment]
> This is completely unrelated to the InfiniteMac project.

I am sorry, but I saw questions related to sheepshaver in Issues and decided to ask.

**Comment by mihaip** [comment]
While Infinite Mac uses SheepShaver under the hood to power some of the machines, I'm not very familiar with the Windows-hosted version. You'll have better luck posting in the E-maculation forums: https://www.emaculation.com/forum/viewforum.php?f=20
