### ISSUE TITLE
adding in futhur help

### ISSUE THREAD

**Issue by Intercity225** [mihaip/infinite-mac#348]
please can you add in more help i have no clue how to connect and further help in the web site would be appreciated thanks

**Comment by Intercity225** [comment]
Sorry for not being clearer. If possible how do I connect to appletalk and the web browser?

**Comment by bshep** [comment]
> Sorry for not being clearer. If possible how do I connect to appletalk and the web browser?

You can only connect using another instance of infinite mac running on another tab or computer. There is no network access to the outside world at this time ( you can access the wider internet or other devices on your network from IM )

To activate appletalk click on ‘customize’ the click ‘enable appletalk’ then type in your zone name. You can do this on multiple tabs or different computers and they will be able to communicate with appletalk.

**Comment by Intercity225** [comment]
Where do I create a zone or is it automatically created? If it’s automatically made then where do I find the zone?

**Comment by bshep** [comment]
> Where do I create a zone or is it automatically created? If it’s automatically made then where do I find the zone?

When you type it into the box as described above it is created.
