### ISSUE TITLE
Power Macintosh G3 Blue & White supposedly hangs while starting up

### ISSUE THREAD

**Issue by Jackgame281** [mihaip/infinite-mac#354]
![Screenshot 2024-12-02 114616](https://github.com/user-attachments/assets/d9337683-d389-4501-82ab-734f3a8617ad)
I recently opened Infinite Mac to try something. I used DingusPPC and the Experimental 'Power Macintosh G3 (Blue & White)' and I understood that it may not work. But the attached image at the top is what I saw when trying to run it. 
![Снимок экрана 2024-12-02 115113](https://github.com/user-attachments/assets/b47630b3-61fc-4566-b2da-c8292461f6fe)
These are the settings I used. 

When I used G3 Beige when running Jaguar, it takes a bit to start up, but it "works" and didn't seem to hang.

**Comment by Jackgame281** [comment]
I also apologize if this isn't very clear.

**Comment by that-ben** [comment]
Hi, Mac OS X (through DingusPPC) is not ready for use.  Some users have got it booting all the way to the desktop, but it's far from being everyone who can and it's only like 1 time out 10.  Even if you reboot it 10 times and finally get it to boot to the desktop, it's gonna be nearly unusable and could freeze at any given moment.

**Comment by Jackgame281** [comment]
I have recently noticed that. I have tried to run DingusPPC with the Beige and Blue & White, but I believe you are correct. It is not ready. Thank you.

**Comment by ColaCaine** [comment]
So how can I run Mac Os X 10.2 Jaguar? What machine DOES work?

**Comment by Jackgame281** [comment]
The best luck I have with a configuration of Power Macintosh G3 (beige) with 256mb of ram. auto screen size, and the 10.2 jaguar disk, obviously.
