### ISSUE TITLE
Emscripten upgrade breaks The Outside World

### ISSUE THREAD

**Issue by Intercity225** [mihaip/infinite-mac#355]
I have recently tried to expand some things using stuffit expander and it hasn't been working - I'm on the most recent version of Microsoft edge and it was on an OS9 instance. I have also tried with an OS8 instance. The instance just froze for a bit and then stuffit quit.

**Comment by that-ben** [comment]
Can you please define those things so we can try to help you:
1) What exact file were you trying to expand? Give the full name and if possible post a link or instructions on how you got the file.
2) What version of Stuffit Expander were you trying to use? Was it part of the Mac OS 9 instance already or is it a version that you imported? Give instructions on how to find the Stuffit Expander app that you used.

Other questions I can answer by myself when I get an answer for 1).

**Comment by Intercity225** [comment]
1: the files were https://macintoshgarden.org/apps/appearance-addons-appearance-manager, and https://macintoshgarden.org/apps/aclock. it was a part of the macos instances when i loaded them and they were in The Outside World > Downloads.

**Comment by that-ben** [comment]
Can you try something before I delve into it? Re-download the .sit files and then before expanding them, move those .sit files to the internal "Macintosh HD" hard drive icon.  Then try to expand them from that location.  Let me know if it works or not, then I will delve into it for you.

**Comment by Intercity225** [comment]
terribly sorry, but i did that, and they still didn't work.

**Comment by that-ben** [comment]
Alright, I tried it and I also get the same result: Stuffit Expander in InfiniteMac doesn't seem to want anything to do with those .sit files.  I'm not 100% sure why, but what I did to quickly mitigate the issue for you is to expand all those .sit files with Stuffit Expander 5.5 under System 7.5.3 (in Basilisk II) and then I made a disk image with all the expanded .sit files that you can mount in InfiniteMac.  Just expand the .zip and drag the resulting .dsk onto InfiniteMac to mount as a virtual CD. Note: I did not include the .dmg file for obvious reasons (it's for OSX, not for OS9).  Enjoy! 😎👍

http://macintoshrepository.org/files/direct/Intercity225.dsk.zip

BTW, if you like vintage Mac OS themes, make sure to check out our interactive 4000 Kaleidoscope schemes that runs in InfiniteMac.  You can apply and try any of the Kaleidoscope schemes simply by double clicking any of them! Good luck not wasting the rest of your day on this, haha! 🤣

https://emulate-in-browser.macintoshrepository.org/?macmodel=7&disk1=K-Schemes.dsk&rom=mac_oldworld_rom4mb.rom&disk2=K-Schemes.dsk

**Comment by mihaip** [comment]
I think something in the Emscripten upgrade from f81035dc1db27bd2e48c3e36bde9b642e51dab0d broke copying of files to The Outside World. I've rolled back to an older version for now, things should work again.

**Comment by that-ben** [comment]
It works for me, now:
<img width="1235" alt="Screenshot 2024-12-11 at 8 54 33 AM" src="https://github.com/user-attachments/assets/f5818bc0-70e2-462f-a57c-a3a6903cae2d" />

**Comment by Intercity225** [comment]
must be a problem on my end then
