### ISSUE TITLE
Kid Pix won't launch due to imagined memory constraints

### ISSUE THREAD

**Issue by dbergey** [mihaip/infinite-mac#37]
When Kid Pix is launched (after switching to 256 colors), it complains that there is not enough memory to run.

**Comment by mihaip** [comment]
For some reason the archive that I'm using for it (see https://github.com/mihaip/infinite-mac/blob/main/Library/Graphics/Kid%20Pix.json) has a very low "Preferred Memory" size. If you do a "Get Info" on it and bump it up to the recommended amount, it should work:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/513813/161361471-4b47bc12-5911-4cd3-84ab-96c4f0528c35.png">

Will look into overriding this and/or finding a different archive.

**Comment by dbergey** [comment]
Ugh I forgot about that setting; it's been too long. Thanks!

**Comment by splorp** [comment]
I tried this suggestion, but still get a type 25 error after launching.

![image](https://user-images.githubusercontent.com/29835/161396193-8d0dd893-307f-42d0-b9a3-6069d4294085.png)

**Comment by mihaip** [comment]
@splorp I think that's a separate issue that's unique to the MacOS 8 image (it also affects Photoshop, see #28). You may have better luck on https://system7.app

**Comment by splorp** [comment]
@mihaip I’ve been meaning to give that a try. Will let you know.
