### ISSUE TITLE
Civilization: Text in main menu + on buttons fails to render

### ISSUE THREAD

**Issue by roughjericho** [mihaip/infinite-mac#40]
![chrome_0402102047009_7FhEki0N5w](https://user-images.githubusercontent.com/32465342/161389921-123e8052-8ad1-4ba2-ac31-ad9e8e574e35.png)
![chrome_0402102328230_CSCbtcsWvK](https://user-images.githubusercontent.com/32465342/161389922-0e526850-b979-4e39-ae13-40e80f8771af.png)

Not aware of what Civilization uses for these.

Additionally, the quit dialog renders text successfully when the "Yes, quit!" radio button is selected- but selecting the other option makes it fail to render again.

I have confirmed this happens on both versions of the site.

**Comment by mihaip** [comment]
Civilization really needs to run in 256 colors. You can switch it via the control strip (lower-left corner). See also #38 (about switching to 256 colors by default).
