### ISSUE TITLE
Slow dissolve transition (eg. in HyperCard)

### ISSUE THREAD

**Issue by gingerbeardman** [mihaip/infinite-mac#42]
This isn't unique to your project, I've seen it in BasiliskII proper. [Apparently](https://github.com/kanjitalk755/macemu/issues/107) the CPU hits 100% during the transition for some reason.

So I'm interested in your thoughts on it?

The attached file will need to be expanded using Stuffit Expander, and opened using HyperCard. Compare the speed of the transition with Mini vMac.

Thoru Yamamoto's "A Little Tree" HyperCard stack
[A Little Tree.sit.zip](https://github.com/mihaip/infinite-mac/files/8403489/A.Little.Tree.sit.zip)

**Comment by gingerbeardman** [comment]
How difficult would it be to test a different, more modern, 68K core?

**Comment by gingerbeardman** [comment]
Turns out this issue was because BasiliskII lacked a high resolution timer, which was present only in SheepShaver.

Fixed a few hours ago in the latest BasiliskII source 
https://github.com/kanjitalk755/macemu/issues/107#issuecomment-1531143919

**Comment by that-ben** [comment]
@mihaip We need this implemented in InfiniteMac! :)

**Comment by mihaip** [comment]
https://github.com/kanjitalk755/macemu/commit/1199f8115e3e8569a7551126f51182183cea5a75 was the commit that fixed this on in the kanjitalk755 fork. I'll look into updating mine with recent changes, but it may require additional work (the timer uses threading, which is not available in the Emscripten setup that I have).

**Comment by mihaip** [comment]
Not actually fixed, even with the picked up change.

**Comment by mihaip** [comment]
@gingerbeardman yes, additional work is required in the WebAssembly version. You can tell because the WebAssembly version of SheepShaver also has slow dissolves, even though the native version did not even before this fix.

**Comment by that-ben** [comment]
Aren't workers basically threads? I'm sorry for the n00bness here, but I would have thought the browser automatically made threads out of JS workers.

**Comment by mihaip** [comment]
@gingerbeardman This should be fixed for real now (at least the dissolves in that HyperCard stack are fast now).

@that-ben: while workers are analogous to threads, they do require some work by the Emscripten compiler to be made to work (see https://emscripten.org/docs/porting/pthreads.html). They also assume that `SharedArrayBuffer` is available, which is not the case for 5-7% of users of Infinite Mac (mostly older versions of Safari, before 15.2). Thus far I have not relied on threads.

**Comment by gingerbeardman** [comment]
Thanks! Neat solution from you. Nice work!
