### ISSUE TITLE
Feature request: Locally hosting instructions? 

### ISSUE THREAD

**Issue by edmundronald** [mihaip/infinite-mac#43]
Could one post instructions -or a link to instructions for locally hosting this on Mac/PC/Linux this in the Readme?

Also, it would be really nice if one could put it on a usb key. 

Edmund

**Comment by mihaip** [comment]
This isn't really meant to be hosted locally -- the main appeal of the project is that it's web-based and requires no setup on the user's part.

If you're looking to run something locally, the traditional emulation options (Basilisk II, SheepShaver, etc.) are all available as native programs for Mac/Windows/Linux.

**Comment by edmundronald** [comment]
Yes, that's exactly my point - it would be nice to be able ot use this on machines without net access or installation
