### ISSUE TITLE
Allow CD-ROM images to be mounted without restarting the simulator (or the Mac)

### ISSUE THREAD

**Issue by mihaip** [mihaip/infinite-mac#49]
We can do some minor surgery to cdrom.cpp to not require that files are present (https://github.com/mihaip/macemu/blob/089f77754b8afc53ac22f24e534f0702c3e09989/BasiliskII/src/cdrom.cpp#L298-L300) and then trigger `CDROMMountVolume` (https://github.com/mihaip/macemu/blob/089f77754b8afc53ac22f24e534f0702c3e09989/BasiliskII/src/cdrom.cpp#L322) when they are actually created.

Followup to 800b508a33fe0e7c56adc5e434f63573c99b0373

**Comment by that-ben** [comment]
This is a really, really welcome improvement! Congratulations on enabling this.
