### ISSUE TITLE
Large icon doesn't fit the macOS icon container shape

### ISSUE THREAD

**Issue by jdsimcoe** [mihaip/infinite-mac#54]
I noticed that the dock icons are not sized relative to the other default macOS icons:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/275617/165589776-880f35ae-af2a-434c-878f-d5f536cdae15.png">

The icon should be 824 pixels within the 1024px frame:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/275617/165589894-618c4b3d-6b9e-4cf3-af9f-bc5593ba452a.png">

Is there any way you could update this?

**Comment by jdsimcoe** [comment]
I fixed it here by copying/pasting into my Figma template:

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/275617/165591175-3b6cfa23-dc74-4840-90dc-015133eeb7ec.png">
[Infinite Mac.iconset.zip](https://github.com/mihaip/infinite-mac/files/8575350/Infinite.Mac.iconset.zip)

You are welcome to use my file.

**Comment by mihaip** [comment]
Thanks for making this. The intent was that the icon shape would line up with iOS icons:

![image](https://user-images.githubusercontent.com/513813/169710975-487858da-e1ba-4979-91b6-69820314639b.png)

Don't think there's a way to do per-platform icons (except perhaps with some user agent detection and serving different files), so this may not be easily fixed.

**Comment by jdsimcoe** [comment]
@mihaip Actually there is a way to do both! [Typefully](https://typefully.com/) is a great example. Here is their `manifest-mac.json` which handles the macOS dock shaped icons:

```
{
  "short_name": "Typefully",
  "name": "Typefully",
  "description": "Distraction-free editor to write & publish tweets and tweetstorms.",
  "icons": [
    {
      "src": "/icon/mac-icon.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
  "start_url": "/",
  "scope": "/",
  "display": "standalone",
  "theme_color": "#1DA1F2",
  "background_color": "#FFFFFF"
}
```
<img width="527" alt="image" src="https://user-images.githubusercontent.com/275617/170105384-40bca157-8d65-491a-9587-78f9543124fe.png">

On iOS for Home Screen shortcuts, they actually still use apple-touch-icon or the newer so you can pass in the iOS shape via the touch icon:

`<link rel="apple-touch-icon" href="/icon/apple-icon.png">`

Which produces this:

![IMG_0805](https://user-images.githubusercontent.com/275617/170105147-261d2e93-e9e3-4b27-9c5f-d93760566506.PNG)
