### ISSUE TITLE
COMMAND key does not work in Firefox under Windows

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#70]
COMMAND key (e.g. COMMAND-W to close a window under the emulated Mac OS) does not work at all in Firefox 106.0 (and possibly other releases) under Windows.  The COMMAND/CONTROL key swap option that's recently been added does not work either.

Note: The rainbow colored Apple symbol that's supposed to be on lower/left corner of the emulator web page doesn't display properly in Firefox under Windows either.  It could be replaced with a small PNG instead to make sure it appears correctly under all platforms and wouldn't realistically take more bytes than the huge CSS rule that's currently not working anyway.

Thanks for putting this incredible WASM emulator together, Mihai.

**Comment by mihaip** [comment]
Thanks for reporting this, the command key should work now. I've filed #76 about the Apple logo.

**Comment by that-ben** [comment]
Thank you for your incredible work on this project.
