### ISSUE TITLE
[Command + B] does unexpected things on Firefox v107 with MacOs 12

### ISSUE THREAD

**Issue by AlfredJKwack** [mihaip/infinite-mac#74]
Steps to reproduce

Run infinite mac.

1. Hit [Command+b] which selects the finder window
2. Click on a note: the letter _B_ gets typed repeatedly
3. Type any letter to stop the repeating entry
4. Hit [Command+b] again. The letter B starts getting printed in the note once more.

This also works with [Command + R]

This issue could not be reproduced on Safari (v15.4) nor Chrome (v108) with MacOs 12

**Comment by mihaip** [comment]
Thanks for reporting this, the command key should work now.

**Comment by AlfredJKwack** [comment]
Confirmed. Thanks @mihaip . Issue resolved.
