### ISSUE TITLE
Add SoundApp

### ISSUE THREAD

**Issue by MaddTheSane** [mihaip/infinite-mac#75]
Please add SoundApp68k and/or SoundAppPPC.
They can be found here: https://www.macintoshrepository.org/1615-soundapp
It's a great sound playback/conversion app.

**Comment by that-ben** [comment]
Works great under system7.app :)

<img src="https://i.ibb.co/NZWxzBD/soundapp.png" alt="" />

**Comment by mihaip** [comment]
Thanks for the suggestion, both 68K and PPC versions have been added.
