### ISSUE TITLE
Cannot mount another disk image after the first restart

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#77]
(EDIT: Forgot to specify in case it's browser related, but this was tested under Firefox 107.0)

In the current release of macos9.app (and possibly older releases as well?) if I drag and drop a disk image onto the emulator and restart it to mount the volume, it works as expected, but then there are 2 unexpected things that happen:

1) If I eject the mounted disk image volume, a second later, it automatically re-mounts.  Tried menu: SPECIAL > EJECT and also dragging it to the Trash.

2) If I want to replace the disk image by another one, I seemingly can't: Dragging a second disk image asks me to restart Infinite Mac, but then the emulator does not restart.  Instead, it hangs permanently and the JS console outputs: Uncaught (in promise) DOMException: Worker.postMessage: attempting to access detached ArrayBuffer.  Manually refreshing the page to reload the emulator re-mounts the first disk image, but not the second one, so I'm stuck with that first disk image forever :P

**Comment by that-ben** [comment]
Here is a MP4 video capture of the 2 issues described above:

https://www.macintoshrepository.org/files/direct/macos9app_20221214-082316.mp4

**Comment by mihaip** [comment]
1 appears to be intentional, at least the native build of SheepShaver has that behavior too.

2 is my bug, I will look into it. It also affects Basilisk II.
