### ISSUE TITLE
No way to power on the mac from the emulator (frozen screen after shutdown with no way to recover)

### ISSUE THREAD

**Issue by TheoCGaming** [mihaip/infinite-mac#78]
Exactly what it says on the box, I can't turn the mac back on after I press the "Shut Down" button in the apple menu.

**Comment by that-ben** [comment]
You could just refresh the page.

**Comment by TheoCGaming** [comment]
Yes, but I'd rather keep what I've done, say if I moved some files around (enabling plugins/addons/etc) or fixed the nonexistent internet connection.

**Comment by that-ben** [comment]
But wouldn't changes get lost when you "shut down" anyway?

**Comment by TheoCGaming** [comment]
No, since the restart button works and changes get saved. (Although restart is technically a warm start... as if that makes a difference to the outcome.)

**Comment by mihaip** [comment]
ab2e48344c3240cdb803ec8520c663a699cea5c6 changed it so that the emulated Mac is closed when shut down. It does mean that any changes to the built-in disk are lost, but if you use a persisted disk (#182), those will be saved.
