### ISSUE TITLE
Whatever the frick happened here.

### ISSUE THREAD

**Issue by MochaChocha667** [mihaip/infinite-mac#82]
I swapped from 256 greys to 1,000s of colours, and this happened.
![Screenshot 2022-12-13 12 28 18 PM](https://user-images.githubusercontent.com/32839663/207324174-87b67d16-43e6-40f4-aa65-cece72e2e443.png)
*Hopefully* you can fix it?

**Comment by mihaip** [comment]
Duplicate of #20
