### ISSUE TITLE
Unable to switch to french keyboard

### ISSUE THREAD

**Issue by jllipatz** [mihaip/infinite-mac#88]
Hello,

The application is amazing! I managed to run some software I made from scratch some times ago.
But unfortunately I had to use a small tool that simulates a keyboard : I didn't find out how to switch to the type of azerty keyboard I have on PC. What is the trick?

Best regards

PS: From the point of view of my application, the emulator runs 10 times slower on the 2,5GHz PC than on the 400MHz G4 tower purchased at end 1999 (still alive!).

**Comment by jllipatz** [comment]
I forgot to write that I was running MacOS9

**Comment by jllipatz** [comment]
Apparently,this is a problem with the Windows version only. I am unable to open the keyboard control panel ("Keyboard preference file in use by another application"). I managed to switch by another way, but there is still a problem with some keys of the keyboard that doesn't match what it is on a mac keyboard. Usually this is solved with a specific KCHR resource

**Comment by mihaip** [comment]
Looks like the preferences file is corrupted -- will deploy a new disk image that has it recreated.
