### ISSUE TITLE
System 6 graphical glitches

### ISSUE THREAD

**Issue by Sgeo** [mihaip/infinite-mac#95]
https://system6.app is unusable

![image](https://user-images.githubusercontent.com/251161/214932637-fa372b10-09ae-4b60-ae7a-5e5ad1724d04.png)

Chrome 109

**Comment by mihaip** [comment]
Looks OK to me:

![image](https://user-images.githubusercontent.com/513813/214935237-f221d1ff-a56a-4dbe-a0cc-8b8269de6abd.png)

This is with Chrome 109.0.5414.119 on macOS 12.6.2 on an M1 MacBook Pro. Where are you running it?

**Comment by Sgeo** [comment]
Windows 10 with a nVidia GeForce RTX 2070.

Just remembered that I had the ANGLE backend set to OpenGL. Changing it to Default resolves the problem.

**Comment by mihaip** [comment]
Thanks for confirming. System 6/Mini vMac ends up using the "dirty rect" option of [putImageData](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/putImageData), which perhaps is buggy in that implementation.

**Comment by terminalgt** [comment]
im getting this kind of graphic glitch
chrome os 105
[Screen recording 2023-02-15 11.41.37 AM.webm](https://user-images.githubusercontent.com/122653158/219135576-b0952090-f7ea-4b5c-bad8-1f6fb4c2bb06.webm)

**Comment by mihaip** [comment]
@terminalgt I don't currently have access to a Chrome OS device. If you visit chrome://flags, do you have a setting for "ANGLE Graphics Backend", and if so, what is it set to?

<img width="737" alt="image" src="https://user-images.githubusercontent.com/513813/219225713-dc736455-fc0c-435c-941f-9ba9bb7beb7a.png">

**Comment by Sgeo** [comment]
Glitching on Chrome on my Pixel 7. As far as I can tell, there is no ANGLE setting on here.

Interestingly, after taking a screenshot and editing, things seem to improve, as though a repaint helped

![Screenshot_20230215-220157](https://user-images.githubusercontent.com/251161/219257738-3bf8d12c-c552-4265-8bf0-71386a34354b.png)
![Screenshot_20230215-220216](https://user-images.githubusercontent.com/251161/219257748-067043d4-6321-4b63-a106-735e29fcfcc3.png)
![Screenshot_20230215-220231](https://user-images.githubusercontent.com/251161/219257764-daf50c5c-6d56-4972-9fb5-176e06d4eb5b.png)
![Screenshot_20230215-220256](https://user-images.githubusercontent.com/251161/219257778-968dff4b-f0fa-4f9a-8ee9-87c475e82af5.png)

**Comment by that-ben** [comment]
This makes me happy to use Firefox and not Chrome.  Wow :P

**Comment by mihaip** [comment]
Will look into detecting this and disabling the dirty rect optimization in that case, since it seems to be pretty common on Android and ChromeOS devices.
