### ISSUE TITLE
How many mac operating system's will there be?

### ISSUE THREAD

**Issue by terminalgt** [mihaip/infinite-mac#99]

**Comment by mihaip** [comment]
I'm hoping to do every single major release of classic Mac OS, though it'll take a while. Based on the compatibility matrix at https://docs.google.com/spreadsheets/d/1us6SCBgVs8NqbxofJXTmHDeK3nKQJpcgya2nWC9_t2w/edit#gid=0, adding Mini vMac (#71) gives very good coverage.
